/* eslint-disable react/jsx-props-no-spreading */
import React from 'react';
import StoryRouter from 'storybook-react-router';
import OrderSingle from './OrderSingle';

export default {
  title: 'Orders/Single Order View',
  component: OrderSingle,
  decorators: [StoryRouter()],
};

const Template = args => <OrderSingle {...args} />;

export const US = Template.bind({});
US.args = {
  config: {
    accountId: '0ea3705f-ccc9-4205-a8bb-c7f5c45939d5',
    userId: '0',
    country: 'US',
    language: 'en',
    variant: 'details',
    formats: { currency: 'USD', date: 'mmm dd yyyy' },
    columns: [
      {
        field: 'item',
        display: 'labels.orders.columnHeaders.item',
        format: { type: '' },
        hiddenColumnView: '',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: '',
        restrictWidth: true,
      },
      {
        field: 'quantity',
        display: 'labels.orders.columnHeaders.quantity',
        format: { type: '' },
        hiddenColumnView: 'mobile',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: '',
        restrictWidth: true,
      },
      {
        field: 'partNumber',
        display: 'labels.orders.columnHeaders.partNumber',
        format: { type: '' },
        hiddenColumnView: 'mobile',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: '',
        restrictWidth: false,
      },
      {
        field: 'description',
        display: 'labels.orders.columnHeaders.description',
        format: { type: '' },
        hiddenColumnView: 'mobile',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: '',
        restrictWidth: false,
      },
      {
        field: 'status',
        display: 'labels.orders.columnHeaders.status',
        format: { type: 'status' },
        hiddenColumnView: 'mobile',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: '',
        restrictWidth: false,
      },
      {
        field: 'unitPrice',
        display: 'labels.orders.columnHeaders.unitPrice',
        format: { type: 'currency' },
        hiddenColumnView: 'mobile',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: 'right',
        restrictWidth: true,
      },
      {
        field: 'totalPrice',
        display: 'labels.orders.columnHeaders.totalPrice',
        format: { type: 'currency' },
        hiddenColumnView: 'mobile',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: 'right',
        restrictWidth: true,
      },
      {
        field: 'detailedInformation',
        display: 'labels.orders.columnHeaders.detailedInformation',
        format: '{type: "compositeInformation"}',
        hiddenColumnView: 'tablet',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: '',
        restrictWidth: false,
      },
      {
        field: 'total',
        display: 'labels.orders.columnHeaders.total',
        format: { type: 'currency' },
        hiddenColumnView: 'tablet',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: 'right',
        restrictWidth: true,
      },
    ],
  },
  data: {
    table: [
      {
        item: 1,
        quantity: 1,
        partNumber: 'Z544552',
        description:
          'CP1000 STANDARD RECHARGEABLE BATTERY MODULE PACKED  (GREY)',
        status: ['01', 'In Progress'],
        unitPrice: '235',
        totalPrice: '235',
        detailedInformation: [
          'Z544552',
          'CP1000 STANDARD RECHARGEABLE BATTERY M…',
        ],
        total: '235',
        headerId: 37160382,
      },
      {
        item: 2,
        quantity: 1,
        partNumber: 'FRT001',
        description: 'FREIGHT',
        status: ['01', 'In Progress'],
        unitPrice: '0',
        totalPrice: '0',
        detailedInformation: [
          'FRT001',
          'FREIGHT',
          'In Progress',
          1,
          '0',
        ],
        total: '0',
        headerId: 37160382,
      },
    ],
    toolbar: {
      prev: 37160523,
      next: 37160523,
      title: 'Order:4118329',
      items: [
        {
          disabled: false,
          linkTo: null,
          onHandle: () => {},
          text: 'Print',
          type: 'printer',
        },
        {
          disabled: false,
          linkTo:
            '/us/en/account/my-profile/orders?account=0ea3705f-ccc9-4205-a8bb-c7f5c45939d5&user=0&order=37160523',
          onHandle: () => {},
          text: 'Prev',
          type: 'chevron-left',
        },
        {
          disabled: false,
          linkTo:
            '/us/en/account/my-profile/orders?account=0ea3705f-ccc9-4205-a8bb-c7f5c45939d5&user=0&order=37160523',
          onHandle: () => {},
          text: 'Next',
          type: 'chevron-right',
        },
      ],
    },
    headerItems: {
      items: [
        {
          id: 'order-name',
          label: 'labels.orders.header.items.for',
          type: 'label',
          value: 'Jeffrey Puterbaugh',
        },
        {
          id: 'order',
          label: 'Order #:',
          type: 'combined-label',
          value: ['4118329', ''],
        },
        {
          id: 'order-date',
          label: 'Order date:',
          type: 'date',
          value: '2021-09-15',
          config: {
            country: 'US',
            language: 'en',
            mask: 'mmm dd yyyy',
          },
        },
        {
          id: 'order-status',
          label: 'Order status:',
          type: 'label-status',
          value: ['01', 'In Progress'],
        },
      ],
    },
    totalData: {
      items: [
        {
          id: 'order-amount',
          label: 'Order amount:',
          value: '235',
        },
        {
          id: 'tax',
          label: 'Tax:',
          value: '0',
        },
        {
          id: 'charges',
          label: 'Charges:',
          value: '0',
        },
        {
          id: 'total',
          label: 'Total:',
          value: '235.00',
        },
      ],
      config: {
        country: 'US',
        language: 'en',
        mask: 'USD',
      },
    },
  },
  labels: {
    'labels.adaptiveforms.personalDetails.dob':
      'labels.adaptiveforms.personalDetails.dob',
    'labels.adaptiveforms.personalDetails.name':
      'the name to display',
    'labels.address.edit.cancel': 'Cancel - drx',
    'labels.address.edit.city': 'City - drx',
    'labels.address.edit.countryOfResidence': 'Country - drx',
    'labels.address.edit.hint': 'labels.address.edit.hint - drx',
    'labels.address.edit.optional': 'optional - drx',
    'labels.address.edit.postalCode': 'postcode - drx',
    'labels.address.edit.prompt': 'labels.address.edit.prompt - drx',
    'labels.address.edit.save': 'Save - drx',
    'labels.address.edit.state': 'state - drx',
    'labels.address.edit.street1': 'street - drx',
    'labels.address.edit.street2': 'street - drx',
    'labels.address.edit.validation.testkey':
      'labels.address.edit.validation.testkey',
    'address.read.address': 'Address',
    'labels.orders.cellDetails.each': 'each',
    'labels.orders.cellDetails.part': 'Part',
    'labels.orders.cellDetails.status': 'Status',
    'labels.orders.columnHeaders.amount': 'Total',
    'labels.orders.columnHeaders.description': 'Description',
    'labels.orders.columnHeaders.detailedInformation': 'Description',
    'labels.orders.columnHeaders.item': 'Item',
    'labels.orders.columnHeaders.orderDate': 'Order date',
    'labels.orders.columnHeaders.orderNumber': 'Order number',
    'labels.orders.columnHeaders.orderNumberOrderDate': 'Order/Date',
    'labels.orders.columnHeaders.partNumber': 'Part number',
    'labels.orders.columnHeaders.quantity': 'Qty',
    'labels.orders.columnHeaders.status': 'Status',
    'labels.orders.columnHeaders.total': 'Total',
    'labels.orders.columnHeaders.totalPrice': 'Total price',
    'labels.orders.columnHeaders.unitPrice': 'Unit price',
    'labels.orders.columnHeaders.view': 'view',
    'labels.orders.error.buttons.backToOrders': 'Back to orders',
    'labels.orders.error.buttons.home': 'Cochlear home',
    'labels.orders.error.buttons.tryAgain': 'Try again',
    'labels.orders.error.errorImageAlt': 'something went wrong',
    'labels.orders.header.items.order.between': '(ref ',
    'labels.orders.header.items.order.between2': 'hello world',
    'labels.orders.header.items.date': 'Order date:',
    'labels.orders.header.items.for':
      'labels.orders.header.items.for',
    'labels.orders.header.items.order': 'Order #:',
    'labels.orders.header.items.orderNumber': '(ref $placeholder$)',
    'labels.orders.header.items.status': 'Order status:',
    'labels.orders.orderlist.title': 'Orders',
    'labels.orders.states.cancelled': 'Cancelled',
    'labels.orders.states.inProgress': 'In Progress',
    'labels.orders.states.shipped': 'Shipped',
    'labels.tabs.promptText': 'Select a recipient...',
    'labels.tabs.promptTextAbbrv': 'recipient...',
    'labels.tabs2.type.recipient': 'Recipients',
    'labels.orders.toolbar.currentText': 'Order:',
    'labels.orders.toolbar.items.next': 'Next',
    'labels.orders.toolbar.items.prev': 'Prev',
    'labels.orders.toolbar.items.print': 'Print',
    'labels.orders.total.items.amount': 'Order amount:',
    'labels.orders.total.items.charges': 'Charges:',
    'labels.orders.total.items.tax': 'Tax:',
    'labels.orders.total.items.total': 'Total:',
    'labels.orders.message':
      'You don’t have any orders from the past 60 days.',
    i18nStamp: 1635205070740,
  },
};

US.storyName = 'US';
