service: '${self:custom.project}-${self:custom.function}-lambda'

custom:
  # project specific variables
  vars: ${file(./variables.json)}
  infoVars: ${file(./aws_infra_parameters.json)}
  resourceVars: ${file(./aws_resource_parameters.json)}
  commonVars: ${file(./lambda_common_env_parameters.json)}
  region: ${env:AWS_REGION}
  environment: ${env:ENVIRONMENT}
  stage: ${env:ENVIRONMENT}
  buildNumber: ${env:CI_PIPELINE_IID}
  project: ${env:PROJECT_CODE}
  function: address
  APIGWAFV2: ${self:custom.resourceVars.apiWafv2}
  kmsArn:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-kms-arn'
  customDomainName:
    'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
  customDomainPath: !Sub ${env:PROVIDER}-${self:custom.vars.releaseVersion}
  apiauthorizerArn: ${env:PROJECT_CODE}-${env:ENVIRONMENT}-apiauthorizer
  deploy_bucket: ${env:DEPLOY_S3_BUCKET}
  cloudWatchRole: !Sub 'arn:aws:iam::${AWS::AccountId}:role/cochlear-general-apigateway-log-role'
  secretName: ${env:PROJECT_CODE}/${env:ENVIRONMENT}/serverless/secrets
  redisHostname: ${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-url
  redisPort: ${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-port
  redisSG: ${env:PROJECT_CODE}-${env:ENVIRONMENT}-redis-security-group

  proxyNamePath: '/address-V1'
  proxyPrefixPath: '/v1/patients/me/address'

  # serverless plugins specific variables
  offline:
    customAuthenticationProvider: '../local-authorizer-${self:custom.environment}'
  serverless-offline:
    httpPort: 3003
    lambdaPort: 3004
    prefix: 'drx/v1/patients/me/address'
    noPrependStageInUrl: true

  logRetentionInDays: 30
  apiStageTags:
    Owner: ${self:custom.vars.Owner}
    Description: ${self:custom.vars.Description}
    Name: ${self:custom.project}-${self:custom.function}-lambda
    Function: Serverless
    Environment: ${self:custom.vars.Environment}
    Product: ${self:custom.vars.Product}
    Resource: DRX
  apigwBinary:
    types: # list of mime-types
      - '*/*'
  prune:
    automatic: true
    number: 3
  associateWaf:
    name: ${self:custom.APIGWAFV2}
    version: V2
  metrics:
    - name: AWSSecretFail
      pattern: '{($.reason="AWS_SECRET_MANGERMENT_FAIL") && ($.result="ERROR")}'
      functions:
        - getUserInfo
      namespace: ${self:custom.commonVars.cloudWatchNameSpace}

provider:
  name: aws
  runtime: nodejs20.x
  region: ${self:custom.region}
  vpc:
    securityGroupIds:
      - ${self:custom.redisSG}
    subnetIds: ${self:custom.infoVars.subnets}
  # versionFunctions: false
  endpointType: regional
  stage: ${self:custom.stage}
  deploymentBucket:
    name: ${self:custom.deploy_bucket} # Deployment bucket name. Default is generated by the framework
    serverSideEncryption: AES256 # when using server-side encryption
  memorySize: 512
  timeout: 25
  logs:
    restApi:
      roleManagedExternally: true
      role: ${self:custom.cloudWatchRole}
  stackTags:
    Owner: ${self:custom.vars.Owner}
    project: ${self:custom.project}
    Resource: DRX
  tags:
    Description: ${self:custom.vars.Description}
    Name: '${self:custom.project}-${self:custom.function}'
    Function: 'Serverless'
    Environment: ${self:custom.environment}
    Product: ${self:custom.vars.Product}
    buildNumber: ${self:custom.buildNumber}
  apiGateway:
    disableDefaultEndpoint: true
  environment:
    AWS_APPCONFIG_EXTENSION_POLL_INTERVAL_SECONDS: 30
    AWS_APPCONFIG_EXTENSION_POLL_TIMEOUT_MILLIS: 3000
    AWS_APPCONFIG_EXTENSION_HTTP_PORT: 2772
    IS_LOCAL: true

plugins:
  # - serverless-plugin-bind-deployment-id
  - serverless-plugin-optimize
  # - serverless-plugin-warmup
  - api-gateway-stage-tag-plugin
  - serverless-plugin-log-retention
  - serverless-prune-plugin
  # - serverless-pseudo-parameters
  - ./serverless-plugin/metric
  - serverless-associate-waf
  - serverless-offline

package: # Optional deployment packaging configuration
  individually: true
  include: # Specify the directories and files which should be included in the deployment package
    - src/**

functions:
  CorsAddressFunction:
    handler: src/cors-handler.handleRequest
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      corsAllowedHeaders: ${self:custom.commonVars.corsAllowedHeaders}
      corsAllowedMethods: ${self:custom.commonVars.corsGETPOSTAllowedMethods}
      corsOrigin: ${self:custom.commonVars.corsOrigin}
      corsMaxAge: ${self:custom.commonVars.corsMaxAge}
    role: lambdaRole
    events:
      - http:
          path: /
          method: OPTIONS
  GetAddress:
    handler: src/addressHandler.getAddress
    layers:
      - arn:aws:lambda:ap-southeast-2:080788657173:layer:AWS-AppConfig-Extension:91
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      boomiOauthEndpoint: ${self:custom.commonVars.boomiOauthEndpoint}
      boomiServiceEndpoint: ${self:custom.commonVars.boomiServiceEndpoint}
      Environment: ${self:custom.environment}
      PMEndpoint: ${self:custom.vars.pmEndpoint}
      SCEndpoint: ${self:custom.commonVars.scEndpoint}
      SFHostname: ${self:custom.commonVars.sfHostname}
      SFClientID: ${self:custom.commonVars.sfClientID}
      SFUsername: ${self:custom.commonVars.sfUsername}
      SMSFIntegration: ${self:custom.secretName}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      userSessionSeconds: ${self:custom.vars.userSessionSeconds}
      tokenSessionSeconds: ${self:custom.vars.tokenSessionSeconds}
      redisTokenKey: ${self:custom.commonVars.redisTokenKey}
      userSessionPrefix: ${self:custom.commonVars.userSessionPrefix}
      releaseVersion: ${self:custom.vars.releaseVersion}
      logLevel: ${self:custom.vars.logLevel}
      appConfigApplicationId: ${self:custom.vars.appConfigApplicationId}
      appConfigEnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
      appConfigUrl: ${self:custom.vars.appConfigUrl}
    role: lambdaRole
    events:
      - http:
          path: /
          method: GET
          cors:
            origins: '*'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken
            allowCredentials: false
          authorizer:
            name: authorizer
            arn: ${self:custom.apiauthorizerArn}
            type: request
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization, method.request.querystring.id
    # warmup:
    #   prewarm: true
    #   enabled:
    #     - uat
    #     - prd
    #     # - dev

  UpdateAddress:
    handler: src/addressHandler.postAddress
    layers:
      - arn:aws:lambda:ap-southeast-2:080788657173:layer:AWS-AppConfig-Extension:91
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      boomiOauthEndpoint: ${self:custom.commonVars.boomiOauthEndpoint}
      boomiServiceEndpoint: ${self:custom.commonVars.boomiServiceEndpoint}
      Environment: ${self:custom.environment}
      SCEndpoint: ${self:custom.commonVars.scEndpoint}
      SFHostname: ${self:custom.commonVars.sfHostname}
      SFClientID: ${self:custom.commonVars.sfClientID}
      SFUsername: ${self:custom.commonVars.sfUsername}
      SMSFIntegration: ${self:custom.secretName}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      userSessionSeconds: ${self:custom.vars.userSessionSeconds}
      tokenSessionSeconds: ${self:custom.vars.tokenSessionSeconds}
      redisTokenKey: ${self:custom.commonVars.redisTokenKey}
      userSessionPrefix: ${self:custom.commonVars.userSessionPrefix}
      releaseVersion: ${self:custom.vars.releaseVersion}
      logLevel: ${self:custom.vars.logLevel}
      appConfigApplicationId: ${self:custom.vars.appConfigApplicationId}
      appConfigEnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
      appConfigUrl: ${self:custom.vars.appConfigUrl}
    role: lambdaRole
    events:
      - http:
          path: /
          method: POST
          request:
            schemas:
              application/json: ${file(updateAddress-post.yml)}
          cors:
            origins: '*'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken
            allowCredentials: false
          authorizer:
            name: authorizer
            arn: ${self:custom.apiauthorizerArn}
            type: request
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
    # warmup:
    #   prewarm: true
    #   enabled:
    #     - uat
    #     - prd
    #     # - dev

  PatchAddress:
    handler: src/addressHandler.patchAddress
    layers:
      - arn:aws:lambda:ap-southeast-2:080788657173:layer:AWS-AppConfig-Extension:91
    kmsKeyArn: ${self:custom.kmsArn}
    environment:
      region: ${self:custom.region}
      boomiOauthEndpoint: ${self:custom.commonVars.boomiOauthEndpoint}
      boomiServiceEndpoint: ${self:custom.commonVars.boomiServiceEndpoint}
      Environment: ${self:custom.environment}
      SCEndpoint: ${self:custom.commonVars.scEndpoint}
      SFHostname: ${self:custom.commonVars.sfHostname}
      SFClientID: ${self:custom.commonVars.sfClientID}
      SFUsername: ${self:custom.commonVars.sfUsername}
      SMSFIntegration: ${self:custom.secretName}
      RedisPort: ${self:custom.redisPort}
      RedisHostname: ${self:custom.redisHostname}
      userSessionSeconds: ${self:custom.vars.userSessionSeconds}
      tokenSessionSeconds: ${self:custom.vars.tokenSessionSeconds}
      redisTokenKey: ${self:custom.commonVars.redisTokenKey}
      userSessionPrefix: ${self:custom.commonVars.userSessionPrefix}
      releaseVersion: ${self:custom.vars.releaseVersion}
      logLevel: ${self:custom.vars.logLevel}
      appConfigApplicationId: ${self:custom.vars.appConfigApplicationId}
      appConfigEnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
      appConfigUrl: ${self:custom.vars.appConfigUrl}
    role: lambdaRole
    events:
      - http:
          path: /
          method: PATCH
          request:
            schemas:
              application/json: ${file(patchAddress-patch.yml)}
          cors:
            origins: '*'
            headers:
              - Content-Type
              - x-api-token
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - authorizationtoken
            allowCredentials: false
          authorizer:
            name: authorizer
            arn: ${self:custom.apiauthorizerArn}
            type: request
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization

## Resources ##
resources:
  Conditions:
    CreateAlarm:
      Fn::Equals:
        - ${self:custom.vars.createAlarms}
        - 'true'

  Resources:
    CustomDomainMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn:
        - 'ApiGatewayDeployment${sls:instanceId}'
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        BasePath: ${self:custom.customDomainPath}
        DomainName:
          ${self:custom.customDomainName}
          # 'Fn::ImportValue': '${env:PROJECT_CODE}-${env:ENVIRONMENT}-api-custom-domain'
        Stage: ${self:custom.stage}

    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

    UpdateAddressLambdaFunctionErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Condition: CreateAlarm
      Properties:
        AlarmActions:
          - ${self:custom.commonVars.alarmSNS}
        AlarmDescription: 'DRX lambda fail'
        AlarmName: !Join
          - '-'
          - - 'DRX-lambda-UpdateAddress-fail'
            - ${self:custom.stage}
            # - ${opt:versionNumber,"0"}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: '1'
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref UpdateAddressLambdaFunction
        Period: '60'
        Statistic: Sum
        Threshold: '1'
        TreatMissingData: 'notBreaching'
        OKActions:
          - ${self:custom.commonVars.alarmSNS}

    PatchAddressLambdaFunctionErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Condition: CreateAlarm
      Properties:
        AlarmActions:
          - ${self:custom.commonVars.alarmSNS}
        AlarmDescription: 'DRX lambda fail'
        AlarmName: !Join
          - '-'
          - - 'DRX-lambda-PatchAddress-fail'
            - ${self:custom.stage}
            # - ${opt:versionNumber,"0"}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: '1'
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref PatchAddressLambdaFunction
        Period: '60'
        Statistic: Sum
        Threshold: '1'
        TreatMissingData: 'notBreaching'
        OKActions:
          - ${self:custom.commonVars.alarmSNS}

    GetAddressLambdaFunctionErrorAlarm:
      Type: AWS::CloudWatch::Alarm
      Condition: CreateAlarm
      Properties:
        AlarmActions:
          - ${self:custom.commonVars.alarmSNS}
        AlarmDescription: 'DRX lambda fail'
        AlarmName: !Join
          - '-'
          - - 'DRX-lambda-GetAddress-fail'
            - ${self:custom.stage}
            # - ${opt:versionNumber,"0"}
        ComparisonOperator: GreaterThanOrEqualToThreshold
        EvaluationPeriods: '1'
        Namespace: AWS/Lambda
        MetricName: Errors
        Dimensions:
          - Name: FunctionName
            Value: !Ref GetAddressLambdaFunction
        Period: '60'
        Statistic: Sum
        Threshold: '1'
        TreatMissingData: 'notBreaching'
        OKActions:
          - ${self:custom.commonVars.alarmSNS}

    lambdaRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /drx/all/
        PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/core/PermissionsBoundary'
        ManagedPolicyArns: [
            'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
          ] ## Allows VPC Execution rights for Lambda
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: LambdaDRX
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Resource: arn:aws:logs:${self:custom.region}:*:log-group:/aws/lambda/*:*:*
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                - Effect: Allow
                  Resource:
                    - arn:aws:ssm:${self:custom.region}:*:parameter/*
                  Action:
                    - ssm:GetParameter
                - Effect: Allow
                  Resource:
                    - arn:aws:secretsmanager:${self:custom.region}:*:*
                  Action:
                    - secretsmanager:GetSecretValue
                - Effect: 'Allow'
                  Resource:
                    - !Sub
                      - 'arn:aws:appconfig:${AWS::Region}:${AWS::AccountId}:application/${ApplicationId}/environment/${EnvironmentId}/configuration/*'
                      - ApplicationId: ${self:custom.vars.appConfigApplicationId}
                        EnvironmentId: ${self:custom.vars.appConfigEnvironmentId}
                  Action:
                    - appconfig:GetLatestConfiguration
                    - appconfig:StartConfigurationSession
    # warmupRole:
    #   Type: AWS::IAM::Role
    #   Properties:
    #     Path: /drx/all/
    #     ManagedPolicyArns: [
    #         'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole',
    #       ] ## Allows VPC Execution rights for Lambda
    #     AssumeRolePolicyDocument:
    #       Version: '2012-10-17'
    #       Statement:
    #         - Effect: Allow
    #           Principal:
    #             Service:
    #               - lambda.amazonaws.com
    #           Action: sts:AssumeRole
    #     Policies:
    #       - PolicyName: LambdaWarmupDRX
    #         PolicyDocument:
    #           Version: '2012-10-17'
    #           Statement:
    #             - Effect: Allow # WarmUp lambda to send logs to CloudWatch
    #               Action:
    #                 - logs:CreateLogGroup
    #                 - logs:CreateLogStream
    #                 - logs:PutLogEvents
    #               Resource:
    #                 - 'Fn::Join':
    #                     - ':'
    #                     - - 'arn:aws:logs'
    #                       - Ref: 'AWS::Region'
    #                       - Ref: 'AWS::AccountId'
    #                       - 'log-group:/aws/lambda/*:*:*'
    #             - Effect: Allow # WarmUp lambda to manage ENIS (only needed if deploying to VPC, https://docs.aws.amazon.com/lambda/latest/dg/vpc.html)
    #               Action:
    #                 - ec2:CreateNetworkInterface
    #                 - ec2:DescribeNetworkInterfaces
    #                 - ec2:DetachNetworkInterface
    #                 - ec2:DeleteNetworkInterface
    #               Resource: '*'
    #             - Effect: 'Allow' # WarmUp lambda to invoke the functions to be warmed
    #               Action:
    #                 - 'lambda:InvokeFunction'
    #               Resource:
    #                 - Fn::Join:
    #                     - ':'
    #                     - - arn:aws:lambda
    #                       - Ref: AWS::Region
    #                       - Ref: AWS::AccountId
    #                       - function:${self:service}-${opt:stage, self:provider.stage}-*
  Outputs:
    RestApiId:
      Description: 'rest api id'
      Value:
        Ref: ApiGatewayRestApi
