const phoneCountryList = [
  {
    callingCode: '93',
    countryCode: 'AF',
    countryName: 'Afghanistan',
    isoNumeric: '004',
    lng: 'fa-AF,ps,uz-AF,tk',
    label: 'Afghanistan',
    value: 'AF',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '358',
    countryCode: 'AX',
    countryName: 'Åland',
    isoNumeric: '248',
    lng: 'sv-AX',
    label: 'Åland',
    value: 'AX',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '355',
    countryCode: 'AL',
    countryName: 'Albania',
    isoNumeric: '008',
    lng: 'sq,el',
    label: 'Albania',
    value: 'AL',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '213',
    countryCode: 'DZ',
    countryName: 'Algeria',
    isoNumeric: '012',
    lng: 'ar-DZ',
    label: 'Algeria',
    value: 'DZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1684',
    countryCode: 'AS',
    countryName: 'American Samoa',
    isoNumeric: '016',
    lng: 'en-AS,sm,to',
    label: 'American Samoa',
    value: 'AS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '376',
    countryCode: 'AD',
    countryName: 'Andorra',
    isoNumeric: '020',
    lng: 'ca',
    label: 'Andorra',
    value: 'AD',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '244',
    countryCode: 'AO',
    countryName: 'Angola',
    isoNumeric: '024',
    lng: 'pt-AO',
    label: 'Angola',
    value: 'AO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1264',
    countryCode: 'AI',
    countryName: 'Anguilla',
    isoNumeric: '660',
    lng: 'en-AI',
    label: 'Anguilla',
    value: 'AI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '672',
    countryCode: 'AQ',
    countryName: 'Antarctica',
    isoNumeric: '010',
    lng: '',
    label: 'Antarctica',
    value: 'AQ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1268',
    countryCode: 'AG',
    countryName: 'Antigua and Barbuda',
    isoNumeric: '028',
    lng: 'en-AG',
    label: 'Antigua and Barbuda',
    value: 'AG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '54',
    countryCode: 'AR',
    countryName: 'Argentina',
    isoNumeric: '032',
    lng: 'es-AR,en,it,de,fr,gn',
    label: 'Argentina',
    value: 'AR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '374',
    countryCode: 'AM',
    countryName: 'Armenia',
    isoNumeric: '051',
    lng: 'hy',
    label: 'Armenia',
    value: 'AM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '297',
    countryCode: 'AW',
    countryName: 'Aruba',
    isoNumeric: '533',
    lng: 'nl-AW,pap,es,en',
    label: 'Aruba',
    value: 'AW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '61',
    countryCode: 'AU',
    countryName: 'Australia',
    isoNumeric: '036',
    lng: 'en-AU',
    label: 'Australia',
    value: 'AU',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '43',
    countryCode: 'AT',
    countryName: 'Austria',
    isoNumeric: '040',
    lng: 'de-AT,hr,hu,sl',
    label: 'Austria',
    value: 'AT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '994',
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    isoNumeric: '031',
    lng: 'az,ru,hy',
    label: 'Azerbaijan',
    value: 'AZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1 242',
    countryCode: 'BS',
    countryName: 'Bahamas',
    isoNumeric: '044',
    lng: 'en-BS',
    label: 'Bahamas',
    value: 'BS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '973',
    countryCode: 'BH',
    countryName: 'Bahrain',
    isoNumeric: '048',
    lng: 'ar-BH,en,fa,ur',
    label: 'Bahrain',
    value: 'BH',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '880',
    countryCode: 'BD',
    countryName: 'Bangladesh',
    isoNumeric: '050',
    lng: 'bn-BD,en',
    label: 'Bangladesh',
    value: 'BD',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1246',
    countryCode: 'BB',
    countryName: 'Barbados',
    isoNumeric: '052',
    lng: 'en-BB',
    label: 'Barbados',
    value: 'BB',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '375',
    countryCode: 'BY',
    countryName: 'Belarus',
    isoNumeric: '112',
    lng: 'be,ru',
    label: 'Belarus',
    value: 'BY',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '32',
    countryCode: 'BE',
    countryName: 'Belgium',
    isoNumeric: '056',
    lng: 'nl-BE,fr-BE,de-BE',
    label: 'Belgium',
    value: 'BE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '501',
    countryCode: 'BZ',
    countryName: 'Belize',
    isoNumeric: '084',
    lng: 'en-BZ,es',
    label: 'Belize',
    value: 'BZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '229',
    countryCode: 'BJ',
    countryName: 'Benin',
    isoNumeric: '204',
    lng: 'fr-BJ',
    label: 'Benin',
    value: 'BJ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1441',
    countryCode: 'BM',
    countryName: 'Bermuda',
    isoNumeric: '060',
    lng: 'en-BM,pt',
    label: 'Bermuda',
    value: 'BM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '975',
    countryCode: 'BT',
    countryName: 'Bhutan',
    isoNumeric: '064',
    lng: 'dz',
    label: 'Bhutan',
    value: 'BT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '591',
    countryCode: 'BO',
    countryName: 'Bolivia',
    isoNumeric: '068',
    lng: 'es-BO,qu,ay',
    label: 'Bolivia',
    value: 'BO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '5997',
    countryCode: 'BQ',
    countryName: 'Bonaire, Sint Eustatius, and Saba',
    isoNumeric: '535',
    lng: 'nl,pap,en',
    label: 'Bonaire, Sint Eustatius, and Saba',
    value: 'BQ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '387',
    countryCode: 'BA',
    countryName: 'Bosnia and Herzegovina',
    isoNumeric: '070',
    lng: 'bs,hr-BA,sr-BA',
    label: 'Bosnia and Herzegovina',
    value: 'BA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '267',
    countryCode: 'BW',
    countryName: 'Botswana',
    isoNumeric: '072',
    lng: 'en-BW,tn-BW',
    label: 'Botswana',
    value: 'BW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '47',
    countryCode: 'BV',
    countryName: 'Bouvet Island',
    isoNumeric: '074',
    lng: '',
    label: 'Bouvet Island',
    value: 'BV',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '55',
    countryCode: 'BR',
    countryName: 'Brazil',
    isoNumeric: '076',
    lng: 'pt-BR,es,en,fr',
    label: 'Brazil',
    value: 'BR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '246',
    countryCode: 'IO',
    countryName: 'British Indian Ocean Territory',
    isoNumeric: '086',
    lng: 'en-IO',
    label: 'British Indian Ocean Territory',
    value: 'IO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1284',
    countryCode: 'VG',
    countryName: 'British Virgin Islands',
    isoNumeric: '092',
    lng: 'en-VG',
    label: 'British Virgin Islands',
    value: 'VG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '673',
    countryCode: 'BN',
    countryName: 'Brunei',
    isoNumeric: '096',
    lng: 'ms-BN,en-BN',
    label: 'Brunei',
    value: 'BN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '359',
    countryCode: 'BG',
    countryName: 'Bulgaria',
    isoNumeric: '100',
    lng: 'bg,tr-BG,rom',
    label: 'Bulgaria',
    value: 'BG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '226',
    countryCode: 'BF',
    countryName: 'Burkina Faso',
    isoNumeric: '854',
    lng: 'fr-BF,mos',
    label: 'Burkina Faso',
    value: 'BF',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '257',
    countryCode: 'BI',
    countryName: 'Burundi',
    isoNumeric: '108',
    lng: 'fr-BI,rn',
    label: 'Burundi',
    value: 'BI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '238',
    countryCode: 'CV',
    countryName: 'Cabo Verde',
    isoNumeric: '132',
    lng: 'pt-CV',
    label: 'Cabo Verde',
    value: 'CV',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '855',
    countryCode: 'KH',
    countryName: 'Cambodia',
    isoNumeric: '116',
    lng: 'km,fr,en',
    label: 'Cambodia',
    value: 'KH',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '237',
    countryCode: 'CM',
    countryName: 'Cameroon',
    isoNumeric: '120',
    lng: 'en-CM,fr-CM',
    label: 'Cameroon',
    value: 'CM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1',
    countryCode: 'CA',
    countryName: 'Canada',
    isoNumeric: '124',
    lng: 'en-CA,fr-CA,iu',
    label: 'Canada',
    value: 'CA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1 345',
    countryCode: 'KY',
    countryName: 'Cayman Islands',
    isoNumeric: '136',
    lng: 'en-KY',
    label: 'Cayman Islands',
    value: 'KY',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '236',
    countryCode: 'CF',
    countryName: 'Central African Republic',
    isoNumeric: '140',
    lng: 'fr-CF,sg,ln,kg',
    label: 'Central African Republic',
    value: 'CF',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '235',
    countryCode: 'TD',
    countryName: 'Chad',
    isoNumeric: '148',
    lng: 'fr-TD,ar-TD,sre',
    label: 'Chad',
    value: 'TD',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '56',
    countryCode: 'CL',
    countryName: 'Chile',
    isoNumeric: '152',
    lng: 'es-CL',
    label: 'Chile',
    value: 'CL',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '86',
    countryCode: 'CN',
    countryName: 'China',
    isoNumeric: '156',
    lng: 'zh-CN,yue,wuu,dta,ug,za',
    label: 'China',
    value: 'CN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '61',
    countryCode: 'CX',
    countryName: 'Christmas Island',
    isoNumeric: '162',
    lng: 'en,zh,ms-CX',
    label: 'Christmas Island',
    value: 'CX',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '61 891',
    countryCode: 'CC',
    countryName: 'Cocos (Keeling) Islands',
    isoNumeric: '166',
    lng: 'ms-CC,en',
    label: 'Cocos (Keeling) Islands',
    value: 'CC',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '57',
    countryCode: 'CO',
    countryName: 'Colombia',
    isoNumeric: '170',
    lng: 'es-CO',
    label: 'Colombia',
    value: 'CO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '269',
    countryCode: 'KM',
    countryName: 'Comoros',
    isoNumeric: '174',
    lng: 'ar,fr-KM',
    label: 'Comoros',
    value: 'KM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '242',
    countryCode: 'CG',
    countryName: 'Congo Republic',
    isoNumeric: '178',
    lng: 'fr-CG,kg,ln-CG',
    label: 'Congo Republic',
    value: 'CG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '682',
    countryCode: 'CK',
    countryName: 'Cook Islands',
    isoNumeric: '184',
    lng: 'en-CK,mi',
    label: 'Cook Islands',
    value: 'CK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '506',
    countryCode: 'CR',
    countryName: 'Costa Rica',
    isoNumeric: '188',
    lng: 'es-CR,en',
    label: 'Costa Rica',
    value: 'CR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '385',
    countryCode: 'HR',
    countryName: 'Croatia',
    isoNumeric: '191',
    lng: 'hr-HR,sr',
    label: 'Croatia',
    value: 'HR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '53',
    countryCode: 'CU',
    countryName: 'Cuba',
    isoNumeric: '192',
    lng: 'es-CU,pap',
    label: 'Cuba',
    value: 'CU',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '599',
    countryCode: 'CW',
    countryName: 'Curaçao',
    isoNumeric: '531',
    lng: 'nl,pap',
    label: 'Curaçao',
    value: 'CW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '357',
    countryCode: 'CY',
    countryName: 'Cyprus',
    isoNumeric: '196',
    lng: 'el-CY,tr-CY,en',
    label: 'Cyprus',
    value: 'CY',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '420',
    countryCode: 'CZ',
    countryName: 'Czechia',
    isoNumeric: '203',
    lng: 'cs,sk',
    label: 'Czechia',
    value: 'CZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '45',
    countryCode: 'DK',
    countryName: 'Denmark',
    isoNumeric: '208',
    lng: 'da-DK,en,fo,de-DK',
    label: 'Denmark',
    value: 'DK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '253',
    countryCode: 'DJ',
    countryName: 'Djibouti',
    isoNumeric: '262',
    lng: 'fr-DJ,ar,so-DJ,aa',
    label: 'Djibouti',
    value: 'DJ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '767',
    countryCode: 'DM',
    countryName: 'Dominica',
    isoNumeric: '212',
    lng: 'en-DM',
    label: 'Dominica',
    value: 'DM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1',
    countryCode: 'DO',
    countryName: 'Dominican Republic',
    isoNumeric: '214',
    lng: 'es-DO',
    label: 'Dominican Republic',
    value: 'DO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '243',
    countryCode: 'CD',
    countryName: 'DR Congo',
    isoNumeric: '180',
    lng: 'fr-CD,ln,ktu,kg,sw,lua',
    label: 'DR Congo',
    value: 'CD',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '593',
    countryCode: 'EC',
    countryName: 'Ecuador',
    isoNumeric: '218',
    lng: 'es-EC',
    label: 'Ecuador',
    value: 'EC',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '20',
    countryCode: 'EG',
    countryName: 'Egypt',
    isoNumeric: '818',
    lng: 'ar-EG,en,fr',
    label: 'Egypt',
    value: 'EG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '503',
    countryCode: 'SV',
    countryName: 'El Salvador',
    isoNumeric: '222',
    lng: 'es-SV',
    label: 'El Salvador',
    value: 'SV',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '240',
    countryCode: 'GQ',
    countryName: 'Equatorial Guinea',
    isoNumeric: '226',
    lng: 'es-GQ,fr,pt',
    label: 'Equatorial Guinea',
    value: 'GQ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '291',
    countryCode: 'ER',
    countryName: 'Eritrea',
    isoNumeric: '232',
    lng: 'aa-ER,ar,tig,kun,ti-ER',
    label: 'Eritrea',
    value: 'ER',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '372',
    countryCode: 'EE',
    countryName: 'Estonia',
    isoNumeric: '233',
    lng: 'et,ru',
    label: 'Estonia',
    value: 'EE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '268',
    countryCode: 'SZ',
    countryName: 'Eswatini',
    isoNumeric: '748',
    lng: 'en-SZ,ss-SZ',
    label: 'Eswatini',
    value: 'SZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '251',
    countryCode: 'ET',
    countryName: 'Ethiopia',
    isoNumeric: '231',
    lng: 'am,en-ET,om-ET,ti-ET,so-ET,sid',
    label: 'Ethiopia',
    value: 'ET',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '500',
    countryCode: 'FK',
    countryName: 'Falkland Islands',
    isoNumeric: '238',
    lng: 'en-FK',
    label: 'Falkland Islands',
    value: 'FK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '298',
    countryCode: 'FO',
    countryName: 'Faroe Islands',
    isoNumeric: '234',
    lng: 'fo,da-FO',
    label: 'Faroe Islands',
    value: 'FO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '679',
    countryCode: 'FJ',
    countryName: 'Fiji',
    isoNumeric: '242',
    lng: 'en-FJ,fj',
    label: 'Fiji',
    value: 'FJ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '358',
    countryCode: 'FI',
    countryName: 'Finland',
    isoNumeric: '246',
    lng: 'fi-FI,sv-FI,smn',
    label: 'Finland',
    value: 'FI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '33',
    countryCode: 'FR',
    countryName: 'France',
    isoNumeric: '250',
    lng: 'fr-FR,frp,br,co,ca,eu,oc',
    label: 'France',
    value: 'FR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '594',
    countryCode: 'GF',
    countryName: 'French Guiana',
    isoNumeric: '254',
    lng: 'fr-GF',
    label: 'French Guiana',
    value: 'GF',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '689',
    countryCode: 'PF',
    countryName: 'French Polynesia',
    isoNumeric: '258',
    lng: 'fr-PF,ty',
    label: 'French Polynesia',
    value: 'PF',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '672',
    countryCode: 'TF',
    countryName: 'French Southern Territories',
    isoNumeric: '260',
    lng: 'fr',
    label: 'French Southern Territories',
    value: 'TF',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '241',
    countryCode: 'GA',
    countryName: 'Gabon',
    isoNumeric: '266',
    lng: 'fr-GA',
    label: 'Gabon',
    value: 'GA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '995',
    countryCode: 'GE',
    countryName: 'Georgia',
    isoNumeric: '268',
    lng: 'ka,ru,hy,az',
    label: 'Georgia',
    value: 'GE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '49',
    countryCode: 'DE',
    countryName: 'Germany',
    isoNumeric: '276',
    lng: 'de',
    label: 'Germany',
    value: 'DE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '233',
    countryCode: 'GH',
    countryName: 'Ghana',
    isoNumeric: '288',
    lng: 'en-GH,ak,ee,tw',
    label: 'Ghana',
    value: 'GH',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '350',
    countryCode: 'GI',
    countryName: 'Gibraltar',
    isoNumeric: '292',
    lng: 'en-GI,es,it,pt',
    label: 'Gibraltar',
    value: 'GI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '30',
    countryCode: 'GR',
    countryName: 'Greece',
    isoNumeric: '300',
    lng: 'el-GR,en,fr',
    label: 'Greece',
    value: 'GR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '299',
    countryCode: 'GL',
    countryName: 'Greenland',
    isoNumeric: '304',
    lng: 'kl,da-GL,en',
    label: 'Greenland',
    value: 'GL',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1473',
    countryCode: 'GD',
    countryName: 'Grenada',
    isoNumeric: '308',
    lng: 'en-GD',
    label: 'Grenada',
    value: 'GD',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '590',
    countryCode: 'GP',
    countryName: 'Guadeloupe',
    isoNumeric: '312',
    lng: 'fr-GP',
    label: 'Guadeloupe',
    value: 'GP',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1',
    countryCode: 'GU',
    countryName: 'Guam',
    isoNumeric: '316',
    lng: 'en-GU,ch-GU',
    label: 'Guam',
    value: 'GU',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '502',
    countryCode: 'GT',
    countryName: 'Guatemala',
    isoNumeric: '320',
    lng: 'es-GT',
    label: 'Guatemala',
    value: 'GT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '44',
    countryCode: 'GG',
    countryName: 'Guernsey',
    isoNumeric: '831',
    lng: 'en,nrf',
    label: 'Guernsey',
    value: 'GG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '224',
    countryCode: 'GN',
    countryName: 'Guinea',
    isoNumeric: '324',
    lng: 'fr-GN',
    label: 'Guinea',
    value: 'GN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '245',
    countryCode: 'GW',
    countryName: 'Guinea-Bissau',
    isoNumeric: '624',
    lng: 'pt-GW,pov',
    label: 'Guinea-Bissau',
    value: 'GW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '592',
    countryCode: 'GY',
    countryName: 'Guyana',
    isoNumeric: '328',
    lng: 'en-GY',
    label: 'Guyana',
    value: 'GY',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '509',
    countryCode: 'HT',
    countryName: 'Haiti',
    isoNumeric: '332',
    lng: 'ht,fr-HT',
    label: 'Haiti',
    value: 'HT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '672',
    countryCode: 'HM',
    countryName: 'Heard and McDonald Islands',
    isoNumeric: '334',
    lng: '',
    label: 'Heard and McDonald Islands',
    value: 'HM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '504',
    countryCode: 'HN',
    countryName: 'Honduras',
    isoNumeric: '340',
    lng: 'es-HN,cab,miq',
    label: 'Honduras',
    value: 'HN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '852',
    countryCode: 'HK',
    countryName: 'Hong Kong',
    isoNumeric: '344',
    lng: 'zh-HK,yue,zh,en',
    label: 'Hong Kong',
    value: 'HK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '36',
    countryCode: 'HU',
    countryName: 'Hungary',
    isoNumeric: '348',
    lng: 'hu-HU',
    label: 'Hungary',
    value: 'HU',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '354',
    countryCode: 'IS',
    countryName: 'Iceland',
    isoNumeric: '352',
    lng: 'is,en,de,da,sv,no',
    label: 'Iceland',
    value: 'IS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '91',
    countryCode: 'IN',
    countryName: 'India',
    isoNumeric: '356',
    lng: 'en-IN,hi,bn,te,mr,ta,ur,gu,kn,ml,or,pa,as,bh,sat,ks,ne,sd,kok,doi,mni,sit,sa,fr,lus,inc',
    label: 'India',
    value: 'IN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '62',
    countryCode: 'ID',
    countryName: 'Indonesia',
    isoNumeric: '360',
    lng: 'id,en,nl,jv',
    label: 'Indonesia',
    value: 'ID',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '98',
    countryCode: 'IR',
    countryName: 'Iran',
    isoNumeric: '364',
    lng: 'fa-IR,ku',
    label: 'Iran',
    value: 'IR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '964',
    countryCode: 'IQ',
    countryName: 'Iraq',
    isoNumeric: '368',
    lng: 'ar-IQ,ku,hy',
    label: 'Iraq',
    value: 'IQ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '353',
    countryCode: 'IE',
    countryName: 'Ireland',
    isoNumeric: '372',
    lng: 'en-IE,ga-IE',
    label: 'Ireland',
    value: 'IE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '44',
    countryCode: 'IM',
    countryName: 'Isle of Man',
    isoNumeric: '833',
    lng: 'en,gv',
    label: 'Isle of Man',
    value: 'IM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '972',
    countryCode: 'IL',
    countryName: 'Israel',
    isoNumeric: '376',
    lng: 'he,ar-IL,en-IL,',
    label: 'Israel',
    value: 'IL',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '39',
    countryCode: 'IT',
    countryName: 'Italy',
    isoNumeric: '380',
    lng: 'it-IT,de-IT,fr-IT,sc,ca,co,sl',
    label: 'Italy',
    value: 'IT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '225',
    countryCode: 'CI',
    countryName: 'Ivory Coast',
    isoNumeric: '384',
    lng: 'fr-CI',
    label: 'Ivory Coast',
    value: 'CI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '876',
    countryCode: 'JM',
    countryName: 'Jamaica',
    isoNumeric: '388',
    lng: 'en-JM',
    label: 'Jamaica',
    value: 'JM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '81',
    countryCode: 'JP',
    countryName: 'Japan',
    isoNumeric: '392',
    lng: 'ja',
    label: 'Japan',
    value: 'JP',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '44',
    countryCode: 'JE',
    countryName: 'Jersey',
    isoNumeric: '832',
    lng: 'en,fr,nrf',
    label: 'Jersey',
    value: 'JE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '962',
    countryCode: 'JO',
    countryName: 'Jordan',
    isoNumeric: '400',
    lng: 'ar-JO,en',
    label: 'Jordan',
    value: 'JO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '7',
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
    isoNumeric: '398',
    lng: 'kk,ru',
    label: 'Kazakhstan',
    value: 'KZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '254',
    countryCode: 'KE',
    countryName: 'Kenya',
    isoNumeric: '404',
    lng: 'en-KE,sw-KE',
    label: 'Kenya',
    value: 'KE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '686',
    countryCode: 'KI',
    countryName: 'Kiribati',
    isoNumeric: '296',
    lng: 'en-KI,gil',
    label: 'Kiribati',
    value: 'KI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '383',
    countryCode: 'XK',
    countryName: 'Kosovo',
    isoNumeric: '0',
    lng: 'sq,sr',
    label: 'Kosovo',
    value: 'XK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '965',
    countryCode: 'KW',
    countryName: 'Kuwait',
    isoNumeric: '414',
    lng: 'ar-KW,en',
    label: 'Kuwait',
    value: 'KW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '996',
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
    isoNumeric: '417',
    lng: 'ky,uz,ru',
    label: 'Kyrgyzstan',
    value: 'KG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '856',
    countryCode: 'LA',
    countryName: 'Laos',
    isoNumeric: '418',
    lng: 'lo,fr,en',
    label: 'Laos',
    value: 'LA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '371',
    countryCode: 'LV',
    countryName: 'Latvia',
    isoNumeric: '428',
    lng: 'lv,ru,lt',
    label: 'Latvia',
    value: 'LV',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '961',
    countryCode: 'LB',
    countryName: 'Lebanon',
    isoNumeric: '422',
    lng: 'ar-LB,fr-LB,en,hy',
    label: 'Lebanon',
    value: 'LB',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '266',
    countryCode: 'LS',
    countryName: 'Lesotho',
    isoNumeric: '426',
    lng: 'en-LS,st,zu,xh',
    label: 'Lesotho',
    value: 'LS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '231',
    countryCode: 'LR',
    countryName: 'Liberia',
    isoNumeric: '430',
    lng: 'en-LR',
    label: 'Liberia',
    value: 'LR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '218',
    countryCode: 'LY',
    countryName: 'Libya',
    isoNumeric: '434',
    lng: 'ar-LY,it,en',
    label: 'Libya',
    value: 'LY',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '423',
    countryCode: 'LI',
    countryName: 'Liechtenstein',
    isoNumeric: '438',
    lng: 'de-LI',
    label: 'Liechtenstein',
    value: 'LI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '370',
    countryCode: 'LT',
    countryName: 'Lithuania',
    isoNumeric: '440',
    lng: 'lt,ru,pl',
    label: 'Lithuania',
    value: 'LT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '352',
    countryCode: 'LU',
    countryName: 'Luxembourg',
    isoNumeric: '442',
    lng: 'lb,de-LU,fr-LU',
    label: 'Luxembourg',
    value: 'LU',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '853',
    countryCode: 'MO',
    countryName: 'Macao',
    isoNumeric: '446',
    lng: 'zh,zh-MO,pt',
    label: 'Macao',
    value: 'MO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '261',
    countryCode: 'MG',
    countryName: 'Madagascar',
    isoNumeric: '450',
    lng: 'fr-MG,mg',
    label: 'Madagascar',
    value: 'MG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '265',
    countryCode: 'MW',
    countryName: 'Malawi',
    isoNumeric: '454',
    lng: 'ny,yao,tum,swk',
    label: 'Malawi',
    value: 'MW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '60',
    countryCode: 'MY',
    countryName: 'Malaysia',
    isoNumeric: '458',
    lng: 'ms-MY,en,zh,ta,te,ml,pa,th',
    label: 'Malaysia',
    value: 'MY',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '960',
    countryCode: 'MV',
    countryName: 'Maldives',
    isoNumeric: '462',
    lng: 'dv,en',
    label: 'Maldives',
    value: 'MV',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '223',
    countryCode: 'ML',
    countryName: 'Mali',
    isoNumeric: '466',
    lng: 'fr-ML,bm',
    label: 'Mali',
    value: 'ML',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '356',
    countryCode: 'MT',
    countryName: 'Malta',
    isoNumeric: '470',
    lng: 'mt,en-MT',
    label: 'Malta',
    value: 'MT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '692',
    countryCode: 'MH',
    countryName: 'Marshall Islands',
    isoNumeric: '584',
    lng: 'mh,en-MH',
    label: 'Marshall Islands',
    value: 'MH',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '596',
    countryCode: 'MQ',
    countryName: 'Martinique',
    isoNumeric: '474',
    lng: 'fr-MQ',
    label: 'Martinique',
    value: 'MQ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '222',
    countryCode: 'MR',
    countryName: 'Mauritania',
    isoNumeric: '478',
    lng: 'ar-MR,fuc,snk,fr,mey,wo',
    label: 'Mauritania',
    value: 'MR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '230',
    countryCode: 'MU',
    countryName: 'Mauritius',
    isoNumeric: '480',
    lng: 'en-MU,bho,fr',
    label: 'Mauritius',
    value: 'MU',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '262',
    countryCode: 'YT',
    countryName: 'Mayotte',
    isoNumeric: '175',
    lng: 'fr-YT',
    label: 'Mayotte',
    value: 'YT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '52',
    countryCode: 'MX',
    countryName: 'Mexico',
    isoNumeric: '484',
    lng: 'es-MX',
    label: 'Mexico',
    value: 'MX',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '691',
    countryCode: 'FM',
    countryName: 'Micronesia',
    isoNumeric: '583',
    lng: 'en-FM,chk,pon,yap,kos,uli,woe,nkr,kpg',
    label: 'Micronesia',
    value: 'FM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '373',
    countryCode: 'MD',
    countryName: 'Moldova',
    isoNumeric: '498',
    lng: 'ro,ru,gag,tr',
    label: 'Moldova',
    value: 'MD',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '377',
    countryCode: 'MC',
    countryName: 'Monaco',
    isoNumeric: '492',
    lng: 'fr-MC,en,it',
    label: 'Monaco',
    value: 'MC',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '976',
    countryCode: 'MN',
    countryName: 'Mongolia',
    isoNumeric: '496',
    lng: 'mn,ru',
    label: 'Mongolia',
    value: 'MN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '382',
    countryCode: 'ME',
    countryName: 'Montenegro',
    isoNumeric: '499',
    lng: 'sr,hu,bs,sq,hr,rom',
    label: 'Montenegro',
    value: 'ME',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1664',
    countryCode: 'MS',
    countryName: 'Montserrat',
    isoNumeric: '500',
    lng: 'en-MS',
    label: 'Montserrat',
    value: 'MS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '212',
    countryCode: 'MA',
    countryName: 'Morocco',
    isoNumeric: '504',
    lng: 'ar-MA,ber,fr',
    label: 'Morocco',
    value: 'MA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '258',
    countryCode: 'MZ',
    countryName: 'Mozambique',
    isoNumeric: '508',
    lng: 'pt-MZ,vmw',
    label: 'Mozambique',
    value: 'MZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '95',
    countryCode: 'MM',
    countryName: 'Myanmar',
    isoNumeric: '104',
    lng: 'my',
    label: 'Myanmar',
    value: 'MM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '264',
    countryCode: 'NA',
    countryName: 'Namibia',
    isoNumeric: '516',
    lng: 'en-NA,af,de,hz,naq',
    label: 'Namibia',
    value: 'NA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '674',
    countryCode: 'NR',
    countryName: 'Nauru',
    isoNumeric: '520',
    lng: 'na,en-NR',
    label: 'Nauru',
    value: 'NR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '977',
    countryCode: 'NP',
    countryName: 'Nepal',
    isoNumeric: '524',
    lng: 'ne,en',
    label: 'Nepal',
    value: 'NP',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '687',
    countryCode: 'NC',
    countryName: 'New Caledonia',
    isoNumeric: '540',
    lng: 'fr-NC',
    label: 'New Caledonia',
    value: 'NC',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '64',
    countryCode: 'NZ',
    countryName: 'New Zealand',
    isoNumeric: '554',
    lng: 'en-NZ,mi',
    label: 'New Zealand',
    value: 'NZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '505',
    countryCode: 'NI',
    countryName: 'Nicaragua',
    isoNumeric: '558',
    lng: 'es-NI,en',
    label: 'Nicaragua',
    value: 'NI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '227',
    countryCode: 'NE',
    countryName: 'Niger',
    isoNumeric: '562',
    lng: 'fr-NE,ha,kr,dje',
    label: 'Niger',
    value: 'NE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '234',
    countryCode: 'NG',
    countryName: 'Nigeria',
    isoNumeric: '566',
    lng: 'en-NG,ha,yo,ig,ff',
    label: 'Nigeria',
    value: 'NG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '683',
    countryCode: 'NU',
    countryName: 'Niue',
    isoNumeric: '570',
    lng: 'niu,en-NU',
    label: 'Niue',
    value: 'NU',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '672',
    countryCode: 'NF',
    countryName: 'Norfolk Island',
    isoNumeric: '574',
    lng: 'en-NF',
    label: 'Norfolk Island',
    value: 'NF',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '850',
    countryCode: 'KP',
    countryName: 'North Korea',
    isoNumeric: '408',
    lng: 'ko-KP',
    label: 'North Korea',
    value: 'KP',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '389',
    countryCode: 'MK',
    countryName: 'North Macedonia',
    isoNumeric: '807',
    lng: 'mk,sq,tr,rmm,sr',
    label: 'North Macedonia',
    value: 'MK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1 670',
    countryCode: 'MP',
    countryName: 'Northern Mariana Islands',
    isoNumeric: '580',
    lng: 'fil,tl,zh,ch-MP,en-MP',
    label: 'Northern Mariana Islands',
    value: 'MP',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '47',
    countryCode: 'NO',
    countryName: 'Norway',
    isoNumeric: '578',
    lng: 'no,nb,nn,se,fi',
    label: 'Norway',
    value: 'NO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '968',
    countryCode: 'OM',
    countryName: 'Oman',
    isoNumeric: '512',
    lng: 'ar-OM,en,bal,ur',
    label: 'Oman',
    value: 'OM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '92',
    countryCode: 'PK',
    countryName: 'Pakistan',
    isoNumeric: '586',
    lng: 'ur-PK,en-PK,pa,sd,ps,brh',
    label: 'Pakistan',
    value: 'PK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '680',
    countryCode: 'PW',
    countryName: 'Palau',
    isoNumeric: '585',
    lng: 'pau,sov,en-PW,tox,ja,fil,zh',
    label: 'Palau',
    value: 'PW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '970',
    countryCode: 'PS',
    countryName: 'Palestine',
    isoNumeric: '275',
    lng: 'ar-PS',
    label: 'Palestine',
    value: 'PS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '507',
    countryCode: 'PA',
    countryName: 'Panama',
    isoNumeric: '591',
    lng: 'es-PA,en',
    label: 'Panama',
    value: 'PA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '675',
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
    isoNumeric: '598',
    lng: 'en-PG,ho,meu,tpi',
    label: 'Papua New Guinea',
    value: 'PG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '595',
    countryCode: 'PY',
    countryName: 'Paraguay',
    isoNumeric: '600',
    lng: 'es-PY,gn',
    label: 'Paraguay',
    value: 'PY',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '51',
    countryCode: 'PE',
    countryName: 'Peru',
    isoNumeric: '604',
    lng: 'es-PE,qu,ay',
    label: 'Peru',
    value: 'PE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '63',
    countryCode: 'PH',
    countryName: 'Philippines',
    isoNumeric: '608',
    lng: 'tl,en-PH,fil,ceb,ilo,hil,war,pam,bik,bcl,pag,mrw,tsg,mdh,cbk,krj,sgd,msb,akl,ibg,yka,mta,abx',
    label: 'Philippines',
    value: 'PH',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '64',
    countryCode: 'PN',
    countryName: 'Pitcairn Islands',
    isoNumeric: '612',
    lng: 'en-PN',
    label: 'Pitcairn Islands',
    value: 'PN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '48',
    countryCode: 'PL',
    countryName: 'Poland',
    isoNumeric: '616',
    lng: 'pl',
    label: 'Poland',
    value: 'PL',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '351',
    countryCode: 'PT',
    countryName: 'Portugal',
    isoNumeric: '620',
    lng: 'pt-PT,mwl',
    label: 'Portugal',
    value: 'PT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1',
    countryCode: 'PR',
    countryName: 'Puerto Rico',
    isoNumeric: '630',
    lng: 'en-PR,es-PR',
    label: 'Puerto Rico',
    value: 'PR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '974',
    countryCode: 'QA',
    countryName: 'Qatar',
    isoNumeric: '634',
    lng: 'ar-QA,es',
    label: 'Qatar',
    value: 'QA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '262',
    countryCode: 'RE',
    countryName: 'Réunion',
    isoNumeric: '638',
    lng: 'fr-RE',
    label: 'Réunion',
    value: 'RE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '40',
    countryCode: 'RO',
    countryName: 'Romania',
    isoNumeric: '642',
    lng: 'ro,hu,rom',
    label: 'Romania',
    value: 'RO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '7',
    countryCode: 'RU',
    countryName: 'Russia',
    isoNumeric: '643',
    lng: 'ru,tt,xal,cau,ady,kv,ce,tyv,cv,udm,tut,mns,bua,myv,mdf,chm,ba,inh,kbd,krc,av,sah,nog',
    label: 'Russia',
    value: 'RU',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '250',
    countryCode: 'RW',
    countryName: 'Rwanda',
    isoNumeric: '646',
    lng: 'rw,en-RW,fr-RW,sw',
    label: 'Rwanda',
    value: 'RW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '590',
    countryCode: 'BL',
    countryName: 'Saint Barthélemy',
    isoNumeric: '652',
    lng: 'fr',
    label: 'Saint Barthélemy',
    value: 'BL',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '290',
    countryCode: 'SH',
    countryName: 'Saint Helena',
    isoNumeric: '654',
    lng: 'en-SH',
    label: 'Saint Helena',
    value: 'SH',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1758',
    countryCode: 'LC',
    countryName: 'Saint Lucia',
    isoNumeric: '662',
    lng: 'en-LC',
    label: 'Saint Lucia',
    value: 'LC',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '590',
    countryCode: 'MF',
    countryName: 'Saint Martin',
    isoNumeric: '663',
    lng: 'fr',
    label: 'Saint Martin',
    value: 'MF',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '508',
    countryCode: 'PM',
    countryName: 'Saint Pierre and Miquelon',
    isoNumeric: '666',
    lng: 'fr-PM',
    label: 'Saint Pierre and Miquelon',
    value: 'PM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '685',
    countryCode: 'WS',
    countryName: 'Samoa',
    isoNumeric: '882',
    lng: 'sm,en-WS',
    label: 'Samoa',
    value: 'WS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '378',
    countryCode: 'SM',
    countryName: 'San Marino',
    isoNumeric: '674',
    lng: 'it-SM',
    label: 'San Marino',
    value: 'SM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '239',
    countryCode: 'ST',
    countryName: 'São Tomé and Príncipe',
    isoNumeric: '678',
    lng: 'pt-ST',
    label: 'São Tomé and Príncipe',
    value: 'ST',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '966',
    countryCode: 'SA',
    countryName: 'Saudi Arabia',
    isoNumeric: '682',
    lng: 'ar-SA',
    label: 'Saudi Arabia',
    value: 'SA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '221',
    countryCode: 'SN',
    countryName: 'Senegal',
    isoNumeric: '686',
    lng: 'fr-SN,wo,fuc,mnk',
    label: 'Senegal',
    value: 'SN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '381',
    countryCode: 'RS',
    countryName: 'Serbia',
    isoNumeric: '688',
    lng: 'sr,hu,bs,rom',
    label: 'Serbia',
    value: 'RS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '248',
    countryCode: 'SC',
    countryName: 'Seychelles',
    isoNumeric: '690',
    lng: 'en-SC,fr-SC',
    label: 'Seychelles',
    value: 'SC',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '232',
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    isoNumeric: '694',
    lng: 'en-SL,men,tem',
    label: 'Sierra Leone',
    value: 'SL',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '65',
    countryCode: 'SG',
    countryName: 'Singapore',
    isoNumeric: '702',
    lng: 'cmn,en-SG,ms-SG,ta-SG,zh-SG',
    label: 'Singapore',
    value: 'SG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1721',
    countryCode: 'SX',
    countryName: 'Sint Maarten',
    isoNumeric: '534',
    lng: 'nl,en',
    label: 'Sint Maarten',
    value: 'SX',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '421',
    countryCode: 'SK',
    countryName: 'Slovakia',
    isoNumeric: '703',
    lng: 'sk,hu',
    label: 'Slovakia',
    value: 'SK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '386',
    countryCode: 'SI',
    countryName: 'Slovenia',
    isoNumeric: '705',
    lng: 'sl,sh',
    label: 'Slovenia',
    value: 'SI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '677',
    countryCode: 'SB',
    countryName: 'Solomon Islands',
    isoNumeric: '090',
    lng: 'en-SB,tpi',
    label: 'Solomon Islands',
    value: 'SB',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '252',
    countryCode: 'SO',
    countryName: 'Somalia',
    isoNumeric: '706',
    lng: 'so-SO,ar-SO,it,en-SO',
    label: 'Somalia',
    value: 'SO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '27',
    countryCode: 'ZA',
    countryName: 'South Africa',
    isoNumeric: '710',
    lng: 'zu,xh,af,nso,en-ZA,tn,st,ts,ss,ve,nr',
    label: 'South Africa',
    value: 'ZA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '500',
    countryCode: 'GS',
    countryName: 'South Georgia and South Sandwich Islands',
    isoNumeric: '239',
    lng: 'en',
    label: 'South Georgia and South Sandwich Islands',
    value: 'GS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '82',
    countryCode: 'KR',
    countryName: 'South Korea',
    isoNumeric: '410',
    lng: 'ko-KR,en',
    label: 'South Korea',
    value: 'KR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '211',
    countryCode: 'SS',
    countryName: 'South Sudan',
    isoNumeric: '728',
    lng: 'en',
    label: 'South Sudan',
    value: 'SS',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '34',
    countryCode: 'ES',
    countryName: 'Spain',
    isoNumeric: '724',
    lng: 'es-ES,ca,gl,eu,oc',
    label: 'Spain',
    value: 'ES',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '94',
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    isoNumeric: '144',
    lng: 'si,ta,en',
    label: 'Sri Lanka',
    value: 'LK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1869',
    countryCode: 'KN',
    countryName: 'St Kitts and Nevis',
    isoNumeric: '659',
    lng: 'en-KN',
    label: 'St Kitts and Nevis',
    value: 'KN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1784',
    countryCode: 'VC',
    countryName: 'St Vincent and Grenadines',
    isoNumeric: '670',
    lng: 'en-VC,fr',
    label: 'St Vincent and Grenadines',
    value: 'VC',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '249',
    countryCode: 'SD',
    countryName: 'Sudan',
    isoNumeric: '729',
    lng: 'ar-SD,en,fia',
    label: 'Sudan',
    value: 'SD',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '597',
    countryCode: 'SR',
    countryName: 'Suriname',
    isoNumeric: '740',
    lng: 'nl-SR,en,srn,hns,jv',
    label: 'Suriname',
    value: 'SR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '4779',
    countryCode: 'SJ',
    countryName: 'Svalbard and Jan Mayen',
    isoNumeric: '744',
    lng: 'no,ru',
    label: 'Svalbard and Jan Mayen',
    value: 'SJ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '46',
    countryCode: 'SE',
    countryName: 'Sweden',
    isoNumeric: '752',
    lng: 'sv-SE,se,sma,fi-SE',
    label: 'Sweden',
    value: 'SE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '41',
    countryCode: 'CH',
    countryName: 'Switzerland',
    isoNumeric: '756',
    lng: 'de-CH,fr-CH,it-CH,rm',
    label: 'Switzerland',
    value: 'CH',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '963',
    countryCode: 'SY',
    countryName: 'Syria',
    isoNumeric: '760',
    lng: 'ar-SY,ku,hy,arc,fr,en',
    label: 'Syria',
    value: 'SY',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '886',
    countryCode: 'TW',
    countryName: 'Taiwan',
    isoNumeric: '158',
    lng: 'zh-TW,zh,nan,hak',
    label: 'Taiwan',
    value: 'TW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '992',
    countryCode: 'TJ',
    countryName: 'Tajikistan',
    isoNumeric: '762',
    lng: 'tg,ru',
    label: 'Tajikistan',
    value: 'TJ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '255',
    countryCode: 'TZ',
    countryName: 'Tanzania',
    isoNumeric: '834',
    lng: 'sw-TZ,en,ar',
    label: 'Tanzania',
    value: 'TZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '66',
    countryCode: 'TH',
    countryName: 'Thailand',
    isoNumeric: '764',
    lng: 'th,en',
    label: 'Thailand',
    value: 'TH',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '220',
    countryCode: 'GM',
    countryName: 'The Gambia',
    isoNumeric: '270',
    lng: 'en-GM,mnk,wof,wo,ff',
    label: 'The Gambia',
    value: 'GM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '31',
    countryCode: 'NL',
    countryName: 'Netherlands',
    isoNumeric: '528',
    lng: 'nl-NL,fy-NL',
    label: 'Netherlands',
    value: 'NL',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '670',
    countryCode: 'TL',
    countryName: 'Timor-Leste',
    isoNumeric: '626',
    lng: 'tet,pt-TL,id,en',
    label: 'Timor-Leste',
    value: 'TL',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '228',
    countryCode: 'TG',
    countryName: 'Togo',
    isoNumeric: '768',
    lng: 'fr-TG,ee,hna,kbp,dag,ha',
    label: 'Togo',
    value: 'TG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '690',
    countryCode: 'TK',
    countryName: 'Tokelau',
    isoNumeric: '772',
    lng: 'tkl,en-TK',
    label: 'Tokelau',
    value: 'TK',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '676',
    countryCode: 'TO',
    countryName: 'Tonga',
    isoNumeric: '776',
    lng: 'to,en-TO',
    label: 'Tonga',
    value: 'TO',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '868',
    countryCode: 'TT',
    countryName: 'Trinidad and Tobago',
    isoNumeric: '780',
    lng: 'en-TT,hns,fr,es,zh',
    label: 'Trinidad and Tobago',
    value: 'TT',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '216',
    countryCode: 'TN',
    countryName: 'Tunisia',
    isoNumeric: '788',
    lng: 'ar-TN,fr',
    label: 'Tunisia',
    value: 'TN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '90',
    countryCode: 'TR',
    countryName: 'Türkiye',
    isoNumeric: '792',
    lng: 'tr-TR,ku,diq,az,av',
    label: 'Türkiye',
    value: 'TR',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '993',
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    isoNumeric: '795',
    lng: 'tk,ru,uz',
    label: 'Turkmenistan',
    value: 'TM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1 649',
    countryCode: 'TC',
    countryName: 'Turks and Caicos Islands',
    isoNumeric: '796',
    lng: 'en-TC',
    label: 'Turks and Caicos Islands',
    value: 'TC',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '688',
    countryCode: 'TV',
    countryName: 'Tuvalu',
    isoNumeric: '798',
    lng: 'tvl,en,sm,gil',
    label: 'Tuvalu',
    value: 'TV',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1',
    countryCode: 'UM',
    countryName: 'U.S. Outlying Islands',
    isoNumeric: '581',
    lng: 'en-UM',
    label: 'U.S. Outlying Islands',
    value: 'UM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1340',
    countryCode: 'VI',
    countryName: 'U.S. Virgin Islands',
    isoNumeric: '850',
    lng: 'en-VI',
    label: 'U.S. Virgin Islands',
    value: 'VI',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '256',
    countryCode: 'UG',
    countryName: 'Uganda',
    isoNumeric: '800',
    lng: 'en-UG,lg,sw,ar',
    label: 'Uganda',
    value: 'UG',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '380',
    countryCode: 'UA',
    countryName: 'Ukraine',
    isoNumeric: '804',
    lng: 'uk,ru-UA,rom,pl,hu',
    label: 'Ukraine',
    value: 'UA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '971',
    countryCode: 'AE',
    countryName: 'United Arab Emirates',
    isoNumeric: '784',
    lng: 'ar-AE,fa,en,hi,ur',
    label: 'United Arab Emirates',
    value: 'AE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '44',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    isoNumeric: '826',
    lng: 'en-GB,cy-GB,gd',
    label: 'United Kingdom',
    value: 'GB',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '1',
    countryCode: 'US',
    countryName: 'United States',
    isoNumeric: '840',
    lng: 'en-US,es-US,haw,fr',
    label: 'United States',
    value: 'US',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '598',
    countryCode: 'UY',
    countryName: 'Uruguay',
    isoNumeric: '858',
    lng: 'es-UY',
    label: 'Uruguay',
    value: 'UY',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '998',
    countryCode: 'UZ',
    countryName: 'Uzbekistan',
    isoNumeric: '860',
    lng: 'uz,ru,tg',
    label: 'Uzbekistan',
    value: 'UZ',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '678',
    countryCode: 'VU',
    countryName: 'Vanuatu',
    isoNumeric: '548',
    lng: 'bi,en-VU,fr-VU',
    label: 'Vanuatu',
    value: 'VU',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '39',
    countryCode: 'VA',
    countryName: 'Vatican City',
    isoNumeric: '336',
    lng: 'la,it,fr',
    label: 'Vatican City',
    value: 'VA',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '58',
    countryCode: 'VE',
    countryName: 'Venezuela',
    isoNumeric: '862',
    lng: 'es-VE',
    label: 'Venezuela',
    value: 'VE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '84',
    countryCode: 'VN',
    countryName: 'Vietnam',
    isoNumeric: '704',
    lng: 'vi,en,fr,zh,km',
    label: 'Vietnam',
    value: 'VN',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '681',
    countryCode: 'WF',
    countryName: 'Wallis and Futuna',
    isoNumeric: '876',
    lng: 'wls,fud,fr-WF',
    label: 'Wallis and Futuna',
    value: 'WF',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '212',
    countryCode: 'EH',
    countryName: 'Western Sahara',
    isoNumeric: '732',
    lng: 'ar,mey',
    label: 'Western Sahara',
    value: 'EH',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '967',
    countryCode: 'YE',
    countryName: 'Yemen',
    isoNumeric: '887',
    lng: 'ar-YE',
    label: 'Yemen',
    value: 'YE',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '260',
    countryCode: 'ZM',
    countryName: 'Zambia',
    isoNumeric: '894',
    lng: 'en-ZM,bem,loz,lun,lue,ny,toi',
    label: 'Zambia',
    value: 'ZM',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
  {
    callingCode: '263',
    countryCode: 'ZW',
    countryName: 'Zimbabwe',
    isoNumeric: '716',
    lng: 'en-ZW,sn,nr,nd',
    label: 'Zimbabwe',
    value: 'ZW',
    disabled: false,
    visible: true,
    countryFlagCdnUrl: '',
  },
];

export default phoneCountryList;
