AWSTemplateFormatVersion: 2010-09-09
Description: >-
  An template that stands up an ElasticCache Replication Group Multi-AZ
  in a particular VPC specifying then a Subnet Group and a Security Group
Parameters:

  SecretManagerAuthCodeName:
    Description: The name for Auth Code that store in secret manager
    Type: String
    Default: cochlear-drx-nonp-redis-auth-code
  CacheNodeType:
    Description: The instance type the nodes will launch under.
    Type: String
    Default: cache.m3.medium
    AllowedValues:
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.m3.medium
      - cache.m3.large
      - cache.m3.xlarge
      - cache.m3.2xlarge
      - cache.r3.large
      - cache.r3.xlarge
      - cache.r3.2xlarge
      - cache.r3.4xlarge
      - cache.r3.8xlarge
  CacheName:
    Description: 'DRX Cache Name'
    Type: 'String'
    Default: 'cochlear-drx-redis'
  EngineVersion:
    Description: 'Redis version'
    Type: String
    Default: '6.x'
    AllowedValues: # aws elasticache describe-cache-engine-versions --engine redis --query "CacheEngineVersions[].EngineVersion"
    - '6.x'
    - '5.0.6'
    - '5.0.4'
    - '5.0.0'
    - '4.0.10'
    - '3.2.6' # 3.2.4 and 3.2.10 do not support encryption 
  TransitEncryption:
    Description: 'Enable encryption for data in transit? When transit encryption is enabled also specify an auth token.'
    Type: 'String'
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  AtRestEncryptionEnabled:
    Description: 'Enable encryption for data at rest When transit encryption is enabled also specify an auth token.'
    Type: 'String'
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'            
  MultiAZSupport:
    Description: >-
      Indicates whether Multi-AZ is enabled. When Multi-AZ is enabled, a
      read-only replica is automatically promoted to a read-write primary
      cluster if the existing primary cluster fails. If you specify true, you
      must specify a value greater than 1 for the NumCacheClusters property.
    Type: String
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  NumCacheClusters:
    Description: >-
      The number of cache clusters for this replication group. If MultiAZ
      support is enabled, you must specify a value greater than 1.
    Default: '2'
    Type: Number
    MinValue: '1'
    MaxValue: '6'      
  RedisPort:
    Description: >-
      The port number on which each member of the replication group accepts
      connections.
    Type: Number
    Default: '6379'
    MinValue: '1'
    MaxValue: '65535'
  ReplicationGroupDescription:
    Description: The description of the replication group.
    Type: String
    Default: DRX replication group
  VpcId:
    Description: The VPC to create this ReplicationGroup under
    Type: 'AWS::EC2::VPC::Id'
  CidrIp:
    Description: The CIDR you want to access to the Replication Group
    Type: String
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    MinLength: '9'
    MaxLength: '18'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x
  SnapshotRetentionLimit:
    Description: >-
      The number of days that ElastiCache retains automatic snapshots before
      deleting them.
    Type: Number
    Default: '7'
  SnapshotWindow:
    Description: >-
      The time range (in UTC) when ElastiCache takes a daily snapshot of your
      node group.
    Type: String
    Default: '05:00-09:00'
    AllowedPattern: '\d{2}:\d{2}-\d{2}:\d{2}'
    ConstraintDescription: 'must be a valid timestamp range, for example 05:00-09:00'
  PreferredMaintenanceWindow:
    Description: >-
      The weekly time range during which system maintenance can occur. Use the
      following format to specify a time range: ddd:hh24:mi-ddd:hh24:mi (24H
      Clock UTC).
    Type: String
    Default: 'sun:22:00-sun:23:30'
    AllowedPattern: >-
      (mon|tue|wed|thu|fri|sat|sun):\d{2}:\d{2}-(mon|tue|wed|thu|fri|sat|sun):\d{2}:\d{2}
    ConstraintDescription: >-
      must be a valid timestamp range with day of week, for example sun:22:00-sun:23:30
  SubnetA:
    Description: >-
      One of the subnets you would like the ReplicationGroup to be created in.
    Type: 'AWS::EC2::Subnet::Id'
  SubnetB:
    Description: >-
      One of the subnets you would like the ReplicationGroup to be created in.
    Type: 'AWS::EC2::Subnet::Id'
  SubnetC:
    Description: >-
      One of the subnets you would like the ReplicationGroup to be created in.
    Type: 'AWS::EC2::Subnet::Id'  
  SecruityGroupName:
    Description: "Security Group Name"
    Type: String 
    Default: cochlear-drx-nonprod-redis
  Project:
    Description: "Project Tag"
    Type: String 
    Default: cochlear-drx
  Environment:
    Description: "Environment Tag"
    Type: String 
    Default: "nonp"
  KMSId:
    Description: "Custom Key Id"
    Type: String 
    Default: "arn:aws:kms:ap-southeast-2:402435212363:key/335f4670-bd19-4490-832c-1a785b01d413"
Resources:
  RedisSecertsManager:
    Type: AWS::SecretsManager::Secret
    Properties: 
      Description: "secret location for Redis"
      GenerateSecretString: 
        ExcludePunctuation: true
      Name: !Sub ${Project}/${Environment}/redis/secrets
      Tags: 
        - Key: Project
          Value: !Ref Project
        - Key: Environment
          Value: !Ref Environment

  SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: !Sub 'Security Group for ${Project} ${Environment} Replication Group'
      SecurityGroupIngress:
        - CidrIp: !Ref CidrIp
          FromPort: !Ref RedisPort
          ToPort: !Ref RedisPort
          IpProtocol: tcp
      VpcId: !Ref VpcId
      Tags:
          - 
            Key: Name
            Value: !Ref SecruityGroupName
          -
            Key: Project
            Value: !Ref Project  
          -
            Key: Environment
            Value: !Ref Environment  
  SubnetGroup:
    Type: 'AWS::ElastiCache::SubnetGroup'
    Properties:
      CacheSubnetGroupName: !Sub 'cochlear-${Project}-${Environment}-redis-subnet-group'
      Description: !Sub 'Subnet Group for ${Project} ${Environment} Replication Group'
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB
        - !Ref SubnetC
      Tags:
          -
            Key: Project
            Value: !Ref Project 
          -
            Key: Environment
            Value: !Ref Environment 
  ReplicationGroup:
    Type: 'AWS::ElastiCache::ReplicationGroup'
    Properties:
      AtRestEncryptionEnabled: !Ref AtRestEncryptionEnabled
      KmsKeyId: !Ref KMSId
      AuthToken: !Sub  '{{resolve:secretsmanager:${Project}/${Environment}/redis/secrets:SecretString}}'
      AutomaticFailoverEnabled: !Ref MultiAZSupport
      MultiAZEnabled: !Ref MultiAZSupport
      CacheNodeType: !Ref CacheNodeType
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: "redis"
      EngineVersion: !Ref EngineVersion
      NumCacheClusters: !Ref NumCacheClusters
      Port: !Ref RedisPort
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      ReplicationGroupId: !Ref CacheName
      ReplicationGroupDescription:  !Ref ReplicationGroupDescription
      SecurityGroupIds: 
        - !GetAtt 
          - SecurityGroup
          - GroupId
      SnapshotRetentionLimit: !Ref SnapshotRetentionLimit
      SnapshotWindow: !Ref SnapshotWindow
      TransitEncryptionEnabled: !Ref TransitEncryption  
      Tags:
          -
            Key: Project
            Value: !Ref Project     
          -
            Key: Environment
            Value: !Ref Environment     
Outputs:
  RedisSecurityGroup: 
    Description: Security Group for Redis
    Value: !GetAtt SecurityGroup.GroupId
    Export:
      Name: !Sub ${Project}-${Environment}-redis-security-group
  RGEndpoint:
    Description: The primary endpoint location
    Value: !Join 
      - ''
      - - 'redis://'
        - !GetAtt 
          - ReplicationGroup
          - PrimaryEndPoint.Address
        - ':'
        - !GetAtt 
          - ReplicationGroup
          - PrimaryEndPoint.Port
  RGURL:
    Description: The primary endpoint URL
    Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Address
    Export:
      Name: !Sub ${Project}-${Environment}-redis-url    
  RGPort: 
    Description: the primary endpoint port
    Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Port
    Export:
      Name: !Sub ${Project}-${Environment}-redis-port
  RedisSecret:
    Description: 'Redis Serverless Secret Manager Id'
    Value:  !Sub ${Project}/${Environment}/redis/secrets
    Export:
      Name: !Sub ${Project}-${Environment}-redis-secret-name