
AWSTemplateFormatVersion: "2010-09-09"
Description: DRX project CMK
Parameters:
    Description:
        Description: Description for Key
        Type: String
        Default: project related Custom Managed Key

    Project: 
        Description: Project Name
        Type: String
        Default: DRX
    Environment: 
        Description: Environment 
        Type: String
        Default: nonp                  
    # ProjectRolePattern:
    #     Description: The Prefix that for Project IAM Role
    #     Type: String
    #     Default: 'drx*'        

Resources:
   ProjectSecret:
        Type: 'AWS::SecretsManager::Secret'
        Properties:
            Name: !Sub ${Project}/${Environment}/serverless/secrets
            Description: !Ref Description
            SecretString: '{"secert1":"value1","secret2":"value2"}'
            Tags:
                - Key: Project
                  Value: !Ref Project 
                - Key: Environment
                  Value: !Ref Environment 
Outputs:
    ProjectSecretArn:
        Description: 'Project Serverless Secret Manager Id'
        Value: !Ref ProjectSecret
    ProjectSecret:
        Description: 'Project Serverless Secret Manager Id'
        Value:  !Sub ${Project}/${Environment}/serverless/secrets
        Export:
          Name: !Sub ${Project}-${Environment}-serverless-secret-name