/* eslint-disable react/jsx-props-no-spreading */
import React from 'react';
import StoryRouter from 'storybook-react-router';
import OrderView from './OrderView';

export default {
  title: 'Orders/Container',
  component: OrderView,
  decorators: [StoryRouter()],
};

const Template = args => <OrderView {...args} />;

export const OrderViewDefault = Template.bind({});
OrderViewDefault.args = {
  config: {
    mode: 'list',
    tabs: {
      accountId: 'e58509d9-a770-43ce-ac35-80c01b9ba24a',
      userId: 0,
      labels: {
        promptText: 'Select a recipient...',
        promptTextAbbrv: 'recipient...',
        type: 'Recipients',
      },
      tabs: [
        {
          firstName: 'Jillian',
          lastName: 'Premer',
          tabIndex: 0,
          type: 'Recipient',
          userId:
            'c8795f03d0e1fb1f3bb750ff3cfabaca2af65a35accdd089b080b55991f28ae5WRCvM2n%2BXQwIUAp%2FZX5jbQ%3D%3Db53c33c6dd925bbea7bee970807e6a2cf9191aa65d6fe11ae965852909b49f05',
        },
        {
          firstName: 'Raymond',
          lastName: 'Stegman',
          tabIndex: 1,
          type: 'Recipient',
          userId:
            'd2151faac97f2f3cad864499b8f2bf7f5439d94f2c7faf893677338d5fb40adaJqd5TlRmIzfea216SawRDA%3D%3De2840e20d1790f6276a100078da7d4ad262ab25c6761ca0145b57ab531348ec3',
        },
      ],
    },
    list: {
      accountId: 'e58509d9-a770-43ce-ac35-80c01b9ba24a',
      userId: 0,
      country: 'US',
      language: 'en',
      variant: 'list',
      formats: {
        currency: 'USD',
        date: 'mmm dd yyyy',
      },
      clickableRow: true,
      columns: [
        {
          field: 'OrderNumberOrderDate',
          display: 'labels.orders.columnHeaders.orderNumberOrderDate',
          format: {
            type: 'dateTimeHybrid',
          },
          hiddenColumnView: 'tablet',
          hiddenColumnLabel: false,
          sortable: true,
          syncSort: 'OrderedDate',
          default: '',
          alignment: '',
          restrictWidth: false,
        },
        {
          field: 'OrderNumber',
          display: 'labels.orders.columnHeaders.orderNumber',
          format: {
            type: '',
          },
          hiddenColumnView: 'mobile',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: '',
          restrictWidth: false,
        },
        {
          field: 'OrderedDate',
          display: 'labels.orders.columnHeaders.orderDate',
          format: {
            type: 'dateTime',
          },
          hiddenColumnView: 'mobile',
          hiddenColumnLabel: false,
          sortable: true,
          syncSort: 'OrderNumberOrderDate',
          default: 'asc',
          alignment: '',
          restrictWidth: false,
        },
        {
          field: 'OrderStatus',
          display: 'labels.orders.columnHeaders.status',
          format: {
            type: 'status',
          },
          hiddenColumnView: '',
          hiddenColumnLabel: false,
          sortable: true,
          syncSort: '',
          default: '',
          alignment: '',
          restrictWidth: false,
        },
        {
          field: 'OrderCharges',
          display: 'labels.orders.columnHeaders.amount',
          format: {
            type: 'currency',
          },
          hiddenColumnView: '',
          hiddenColumnLabel: false,
          sortable: true,
          syncSort: '',
          default: '',
          alignment: 'right',
          restrictWidth: true,
        },
        {
          field: 'view',
          display: 'labels.orders.columnHeaders.view',
          format: {
            type: 'orderLink',
          },
          hiddenColumnView: '',
          hiddenColumnLabel: true,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: '',
          restrictWidth: true,
        },
      ],
      handleSortDataChange: () => {},
    },
    details: {
      accountId: 'e58509d9-a770-43ce-ac35-80c01b9ba24a',
      userId: 0,
      country: 'US',
      language: 'en',
      variant: 'details',
      formats: {
        currency: 'USD',
        date: 'mmm dd yyyy',
      },
      columns: [
        {
          field: 'item',
          display: 'labels.orders.columnHeaders.item',
          format: {
            type: '',
          },
          hiddenColumnView: '',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: '',
          restrictWidth: true,
        },
        {
          field: 'quantity',
          display: 'labels.orders.columnHeaders.quantity',
          format: {
            type: '',
          },
          hiddenColumnView: 'mobile',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: '',
          restrictWidth: true,
        },
        {
          field: 'partNumber',
          display: 'labels.orders.columnHeaders.partNumber',
          format: {
            type: '',
          },
          hiddenColumnView: 'mobile',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: '',
          restrictWidth: false,
        },
        {
          field: 'description',
          display: 'labels.orders.columnHeaders.description',
          format: {
            type: '',
          },
          hiddenColumnView: 'mobile',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: '',
          restrictWidth: false,
        },
        {
          field: 'status',
          display: 'labels.orders.columnHeaders.status',
          format: {
            type: 'status',
          },
          hiddenColumnView: 'mobile',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: '',
          restrictWidth: false,
        },
        {
          field: 'unitPrice',
          display: 'labels.orders.columnHeaders.unitPrice',
          format: {
            type: 'currency',
          },
          hiddenColumnView: 'mobile',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: 'right',
          restrictWidth: true,
        },
        {
          field: 'totalPrice',
          display: 'labels.orders.columnHeaders.totalPrice',
          format: {
            type: 'currency',
          },
          hiddenColumnView: 'mobile',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: 'right',
          restrictWidth: true,
        },
        {
          field: 'detailedInformation',
          display: 'labels.orders.columnHeaders.detailedInformation',
          format: {
            type: 'compositeInformation',
          },
          hiddenColumnView: 'tablet',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: '',
          restrictWidth: false,
        },
        {
          field: 'total',
          display: 'labels.orders.columnHeaders.total',
          format: {
            type: 'currency',
          },
          hiddenColumnView: 'tablet',
          hiddenColumnLabel: false,
          sortable: false,
          syncSort: '',
          default: '',
          alignment: 'right',
          restrictWidth: true,
        },
      ],
    },
    errorView: {},
    isError: false,
    isLoading: false,
    handleQueryParams: () => {},
  },
  data: {
    list: {
      table: [
        {
          OrderNumberOrderDate: ['2021-10-11', '00006619'],
          OrderNo: '4118435',
          OrderNumber: '00006619',
          OrderedDate: '2021-10-11',
          OrderStatus: ['01', 'In Progress'],
          OrderCharges: '55.59',
          view: 37163018,
          HeaderId: 37163018,
          LimitedOrderTaxesTotal: '3.64',
          LimitedOrderChargesTotal: '0',
          LimitedOrderLinesTotal: '51.95',
          OnlineStoreOrderNumber: '00006619',
          LimitedOrderTotal: '55.59',
        },
        {
          OrderNumberOrderDate: ['2021-10-11', '00006618'],
          OrderNo: '4118434',
          OrderNumber: '00006618',
          OrderedDate: '2021-10-11',
          OrderStatus: ['01', 'In Progress'],
          OrderCharges: '56.61',
          view: 37163017,
          HeaderId: 37163017,
          LimitedOrderTaxesTotal: '3.71',
          LimitedOrderChargesTotal: '0',
          LimitedOrderLinesTotal: '52.9',
          OnlineStoreOrderNumber: '00006618',
          LimitedOrderTotal: '56.61',
        },
        {
          OrderNumberOrderDate: ['2021-10-19', '00022803'],
          OrderNo: '4118474',
          OrderNumber: '00022803',
          OrderedDate: '2021-10-19',
          OrderStatus: ['01', 'In Progress'],
          OrderCharges: '106.89',
          view: 37163365,
          HeaderId: 37163365,
          LimitedOrderTaxesTotal: '6.99',
          LimitedOrderChargesTotal: '0',
          LimitedOrderLinesTotal: '99.9',
          OnlineStoreOrderNumber: '00022803',
          LimitedOrderTotal: '106.89',
        },
        {
          OrderNumberOrderDate: ['2021-10-20', '00006822'],
          OrderNo: '4118480',
          OrderNumber: '00006822',
          OrderedDate: '2021-10-20',
          OrderStatus: ['01', 'In Progress'],
          OrderCharges: '66.29',
          view: 37163371,
          HeaderId: 37163371,
          LimitedOrderTaxesTotal: '4.34',
          LimitedOrderChargesTotal: '0',
          LimitedOrderLinesTotal: '61.95',
          OnlineStoreOrderNumber: '00006822',
          LimitedOrderTotal: '66.29',
        },
        {
          OrderNumberOrderDate: ['2021-10-20', '00006819'],
          OrderNo: '4118479',
          OrderNumber: '00006819',
          OrderedDate: '2021-10-20',
          OrderStatus: ['01', 'In Progress'],
          OrderCharges: '56.61',
          view: 37163370,
          HeaderId: 37163370,
          LimitedOrderTaxesTotal: '3.71',
          LimitedOrderChargesTotal: '0',
          LimitedOrderLinesTotal: '52.9',
          OnlineStoreOrderNumber: '00006819',
          LimitedOrderTotal: '56.61',
        },
        {
          OrderNumberOrderDate: ['2021-10-20', '00006818'],
          OrderNo: '4118478',
          OrderNumber: '00006818',
          OrderedDate: '2021-10-20',
          OrderStatus: ['01', 'In Progress'],
          OrderCharges: '56.61',
          view: 37163369,
          HeaderId: 37163369,
          LimitedOrderTaxesTotal: '3.71',
          LimitedOrderChargesTotal: '0',
          LimitedOrderLinesTotal: '52.9',
          OnlineStoreOrderNumber: '00006818',
          LimitedOrderTotal: '56.61',
        },
      ],
    },
    details: {
      table: [],
      toolbar: {
        next: '',
        prev: '',
        items: '[]',
        title: '',
      },
      headerItems: {
        items: '[]',
      },
      totalData: {
        items: '[]',
      },
    },
  },
  labels: {
    'labels.adaptiveforms.personalDetails.dob':
      'labels.adaptiveforms.personalDetails.dob',
    'labels.adaptiveforms.personalDetails.name':
      'the name to display',
    'labels.address.edit.cancel': 'Cancel - drx',
    'labels.address.edit.city': 'City - drx',
    'labels.address.edit.countryOfResidence': 'Country - drx',
    'labels.address.edit.hint': 'labels.address.edit.hint - drx',
    'labels.address.edit.optional': 'optional - drx',
    'labels.address.edit.postalCode': 'postcode - drx',
    'labels.address.edit.prompt': 'labels.address.edit.prompt - drx',
    'labels.address.edit.save': 'Save - drx',
    'labels.address.edit.state': 'state - drx',
    'labels.address.edit.street1': 'street - drx',
    'labels.address.edit.street2': 'street - drx',
    'labels.address.edit.validation.testkey':
      'labels.address.edit.validation.testkey',
    'address.read.address': 'Address',
    'labels.orders.cellDetails.each': 'each',
    'labels.orders.cellDetails.part': 'Part',
    'labels.orders.cellDetails.status': 'Status',
    'labels.orders.columnHeaders.amount': 'Total',
    'labels.orders.columnHeaders.description': 'Description',
    'labels.orders.columnHeaders.detailedInformation': 'Description',
    'labels.orders.columnHeaders.item': 'Item',
    'labels.orders.columnHeaders.orderDate': 'Order date',
    'labels.orders.columnHeaders.orderNumber': 'Order number',
    'labels.orders.columnHeaders.orderNumberOrderDate': 'Order/Date',
    'labels.orders.columnHeaders.partNumber': 'Part number',
    'labels.orders.columnHeaders.quantity': 'Qty',
    'labels.orders.columnHeaders.status': 'Status',
    'labels.orders.columnHeaders.total': 'Total',
    'labels.orders.columnHeaders.totalPrice': 'Total price',
    'labels.orders.columnHeaders.unitPrice': 'Unit price',
    'labels.orders.columnHeaders.view': 'view',
    'labels.orders.error.buttons.backToOrders': 'Back to orders',
    'labels.orders.error.buttons.home': 'Cochlear home',
    'labels.orders.error.buttons.tryAgain': 'Try again',
    'labels.orders.error.errorImageAlt': 'something went wrong',
    'labels.orders.header.items.order.between': '(ref ',
    'labels.orders.header.items.order.between2': 'hello world',
    'labels.orders.header.items.date': 'Order date:',
    'labels.orders.header.items.for':
      'labels.orders.header.items.for',
    'labels.orders.header.items.order': 'Order #:',
    'labels.orders.header.items.orderNumber': '(ref $placeholder$)',
    'labels.orders.header.items.status': 'Order status:',
    'labels.orders.orderlist.title': 'Orders',
    'labels.orders.states.cancelled': 'Cancelled',
    'labels.orders.states.inProgress': 'In Progress',
    'labels.orders.states.shipped': 'Shipped',
    'labels.tabs.promptText': 'Select a recipient...',
    'labels.tabs.promptTextAbbrv': 'recipient...',
    'labels.tabs2.type.recipient': 'Recipients',
    'labels.orders.toolbar.currentText': 'Order:',
    'labels.orders.toolbar.items.next': 'Next',
    'labels.orders.toolbar.items.prev': 'Prev',
    'labels.orders.toolbar.items.print': 'Print',
    'labels.orders.total.items.amount': 'Order amount:',
    'labels.orders.total.items.charges': 'Charges:',
    'labels.orders.total.items.tax': 'Tax:',
    'labels.orders.total.items.total': 'Total:',
    'labels.orders.message':
      'You don’t have any orders from the past 60 days.',
    i18nStamp: 1635208961157,
  },
};
OrderViewDefault.storyName = 'Tabs';
