/* eslint-disable react/jsx-props-no-spreading */
import React from 'react';
import StoryRouter from 'storybook-react-router';
import OrderList from './OrderList';

export default {
  title: 'Orders/Orders List',
  component: OrderList,
  decorators: [StoryRouter()],
};

const Template = args => <OrderList {...args} />;

export const US = Template.bind({});
US.args = {
  config: {
    accountId: '0ea3705f-ccc9-4205-a8bb-c7f5c45939d5',
    userId: 0,
    country: 'US',
    language: 'en',
    variant: 'list',
    formats: { currency: 'USD', date: 'mmm dd yyyy' },
    clickableRow: true,
    columns: [
      {
        field: 'OrderNumberOrderDate',
        display: 'labels.orders.columnHeaders.orderNumberOrderDate',
        format: { type: 'dateTimeHybrid' },
        hiddenColumnView: 'tablet',
        hiddenColumnLabel: false,
        sortable: true,
        syncSort: 'OrderedDate',
        default: '',
        alignment: '',
        restrictWidth: false,
      },
      {
        field: 'OrderNumber',
        display: 'labels.orders.columnHeaders.orderNumber',
        format: { type: '' },
        hiddenColumnView: 'mobile',
        hiddenColumnLabel: false,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: '',
        restrictWidth: false,
      },
      {
        field: 'OrderedDate',
        display: 'labels.orders.columnHeaders.orderDate',
        format: { type: 'dateTime' },
        hiddenColumnView: 'mobile',
        hiddenColumnLabel: false,
        sortable: true,
        syncSort: 'OrderNumberOrderDate',
        default: 'asc',
        alignment: '',
        restrictWidth: false,
      },
      {
        field: 'OrderStatus',
        display: 'labels.orders.columnHeaders.status',
        format: { type: 'status' },
        hiddenColumnView: '',
        hiddenColumnLabel: false,
        sortable: true,
        syncSort: '',
        default: '',
        alignment: '',
        restrictWidth: false,
      },
      {
        field: 'OrderCharges',
        display: 'labels.orders.columnHeaders.amount',
        format: { type: 'currency' },
        hiddenColumnView: '',
        hiddenColumnLabel: false,
        sortable: true,
        syncSort: '',
        default: '',
        alignment: 'right',
        restrictWidth: true,
      },
      {
        field: 'view',
        display: 'labels.orders.columnHeaders.view',
        format: { type: 'orderLink' },
        hiddenColumnView: '',
        hiddenColumnLabel: true,
        sortable: false,
        syncSort: '',
        default: '',
        alignment: '',
        restrictWidth: true,
      },
    ],
    handleSortDataChange: () => {},
  },
  labels: {
    'labels.adaptiveforms.personalDetails.dob':
      'labels.adaptiveforms.personalDetails.dob',
    'labels.adaptiveforms.personalDetails.name':
      'the name to display',
    'labels.address.edit.cancel': 'Cancel - drx',
    'labels.address.edit.city': 'City - drx',
    'labels.address.edit.countryOfResidence': 'Country - drx',
    'labels.address.edit.hint': 'labels.address.edit.hint - drx',
    'labels.address.edit.optional': 'optional - drx',
    'labels.address.edit.postalCode': 'postcode - drx',
    'labels.address.edit.prompt': 'labels.address.edit.prompt - drx',
    'labels.address.edit.save': 'Save - drx',
    'labels.address.edit.state': 'state - drx',
    'labels.address.edit.street1': 'street - drx',
    'labels.address.edit.street2': 'street - drx',
    'labels.address.edit.validation.testkey':
      'labels.address.edit.validation.testkey',
    'address.read.address': 'Address',
    'labels.orders.cellDetails.each': 'each',
    'labels.orders.cellDetails.part': 'Part',
    'labels.orders.cellDetails.status': 'Status',
    'labels.orders.columnHeaders.amount': 'Total',
    'labels.orders.columnHeaders.description': 'Description',
    'labels.orders.columnHeaders.detailedInformation': 'Description',
    'labels.orders.columnHeaders.item': 'Item',
    'labels.orders.columnHeaders.orderDate': 'Order date',
    'labels.orders.columnHeaders.orderNumber': 'Order number',
    'labels.orders.columnHeaders.orderNumberOrderDate': 'Order/Date',
    'labels.orders.columnHeaders.partNumber': 'Part number',
    'labels.orders.columnHeaders.quantity': 'Qty',
    'labels.orders.columnHeaders.status': 'Status',
    'labels.orders.columnHeaders.total': 'Total',
    'labels.orders.columnHeaders.totalPrice': 'Total price',
    'labels.orders.columnHeaders.unitPrice': 'Unit price',
    'labels.orders.columnHeaders.view': 'view',
    'labels.orders.error.buttons.backToOrders': 'Back to orders',
    'labels.orders.error.buttons.home': 'Cochlear home',
    'labels.orders.error.buttons.tryAgain': 'Try again',
    'labels.orders.error.errorImageAlt': 'something went wrong',
    'labels.orders.header.items.order.between': '(ref ',
    'labels.orders.header.items.order.between2': 'hello world',
    'labels.orders.header.items.date': 'Order date:',
    'labels.orders.header.items.for':
      'labels.orders.header.items.for',
    'labels.orders.header.items.order': 'Order #:',
    'labels.orders.header.items.orderNumber': '(ref $placeholder$)',
    'labels.orders.header.items.status': 'Order status:',
    'labels.orders.orderlist.title': 'Orders',
    'labels.orders.states.cancelled': 'Cancelled',
    'labels.orders.states.inProgress': 'In Progress',
    'labels.orders.states.shipped': 'Shipped',
    'labels.tabs.promptText': 'Select a recipient...',
    'labels.tabs.promptTextAbbrv': 'recipient...',
    'labels.tabs2.type.recipient': 'Recipients',
    'labels.orders.toolbar.currentText': 'Order:',
    'labels.orders.toolbar.items.next': 'Next',
    'labels.orders.toolbar.items.prev': 'Prev',
    'labels.orders.toolbar.items.print': 'Print',
    'labels.orders.total.items.amount': 'Order amount:',
    'labels.orders.total.items.charges': 'Charges:',
    'labels.orders.total.items.tax': 'Tax:',
    'labels.orders.total.items.total': 'Total:',
    'labels.orders.message':
      'You don’t have any orders from the past 60 days.',
    i18nStamp: 1635205070740,
  },
  data: {
    table: [
      {
        OrderNumberOrderDate: ['2021-11-22', '4066419'],
        OrderNo: '4066419',
        OrderNumber: '4066419',
        OrderedDate: '2021-11-22',
        OrderStatus: ['02', 'Cancelled'],
        OrderCharges: '0.00',
        view: 35077105,
        HeaderId: 35077105,
        LimitedOrderTaxesTotal: '0',
        LimitedOrderChargesTotal: '0',
        LimitedOrderLinesTotal: '0',
        OnlineStoreOrderNumber: null,
        LimitedOrderTotal: '0.00',
      },
      {
        OrderNumberOrderDate: ['2021-11-12', '4066198'],
        OrderNo: '4066198',
        OrderNumber: '4066198',
        OrderedDate: '2021-11-12',
        OrderStatus: ['01', 'In Progress'],
        OrderCharges: '687.20',
        view: 35073661,
        HeaderId: 35073661,
        LimitedOrderTaxesTotal: '32.25',
        LimitedOrderChargesTotal: '9.95',
        LimitedOrderLinesTotal: '645',
        OnlineStoreOrderNumber: null,
        LimitedOrderTotal: '687.20',
      },
      {
        OrderNumberOrderDate: ['2021-11-12', '4066197'],
        OrderNo: '4066197',
        OrderNumber: '4066197',
        OrderedDate: '2021-11-12',
        OrderStatus: ['01', 'In Progress'],
        OrderCharges: '36.20',
        view: 35073658,
        HeaderId: 35073658,
        LimitedOrderTaxesTotal: '1.25',
        LimitedOrderChargesTotal: '9.95',
        LimitedOrderLinesTotal: '25',
        OnlineStoreOrderNumber: null,
        LimitedOrderTotal: '36.20',
      },
      {
        OrderNumberOrderDate: ['2021-11-12', '4066163'],
        OrderNo: '4066163',
        OrderNumber: '4066163',
        OrderedDate: '2021-11-12',
        OrderStatus: ['01', 'In Progress'],
        OrderCharges: '450.95',
        view: 35073356,
        HeaderId: 35073356,
        LimitedOrderTaxesTotal: '21',
        LimitedOrderChargesTotal: '9.95',
        LimitedOrderLinesTotal: '420',
        OnlineStoreOrderNumber: null,
        LimitedOrderTotal: '450.95',
      },
      {
        OrderNumberOrderDate: ['2021-10-25', 'US20005607'],
        OrderNo: '4065971',
        OrderNumber: 'US20005607',
        OrderedDate: '2021-10-25',
        OrderStatus: ['01', 'In Progress'],
        OrderCharges: '259.00',
        view: 35070318,
        HeaderId: 35070318,
        LimitedOrderTaxesTotal: '0',
        LimitedOrderChargesTotal: '0',
        LimitedOrderLinesTotal: '259',
        OnlineStoreOrderNumber: 'US20005607',
        LimitedOrderTotal: '259.00',
      },
      {
        OrderNumberOrderDate: ['2021-10-22', '4065899'],
        OrderNo: '4065899',
        OrderNumber: '4065899',
        OrderedDate: '2021-10-22',
        OrderStatus: ['01', 'In Progress'],
        OrderCharges: '545.00',
        view: 35067233,
        HeaderId: 35067233,
        LimitedOrderTaxesTotal: '45',
        LimitedOrderChargesTotal: '0',
        LimitedOrderLinesTotal: '500',
        OnlineStoreOrderNumber: null,
        LimitedOrderTotal: '545.00',
      },
    ],
  },
};
US.storyName = 'US';
