const fs = require('fs');
const path = require('path');
const packageConfig = require('../package.json');

/* eslint-disable no-console */

/**
 * Generate config
 * The object returned from this function will be made available by importing src/temp/config.js.
 * This is executed prior to the build running, so it's a way to inject environment or build config-specific
 * settings as variables into the JSS app.
 * NOTE! Any configs returned here will be written into the client-side JS bundle. DO NOT PUT SECRETS HERE.
 * @param {object} configOverrides Keys in this object will override any equivalent global config keys.
 */
module.exports = function generateConfig(configOverrides) {
  const defaultConfig = {
    sitecoreApiKey: 'no-api-key-set',
    sitecoreApiHost: '',
    jssAppName: 'Unknown',
  };

  // require + combine config sources
  const scjssConfig = transformScJssConfig();
  const packageJson = transformPackageConfig();

  // optional:
  // do any other dynamic config source (e.g. environment-specific config files)
  // Object.assign merges the objects in order, so the
  // package.json config can override the calculated config,
  // scjssconfig.json overrides it,
  // and finally config passed in the configOverrides param wins.
  const config = Object.assign(
    defaultConfig,
    scjssConfig,
    packageJson,
    configOverrides,
  );

  // The GraphQL endpoint is an example of making a _computed_ config setting
  // based on other config settings.
  addGraphQLConfig(config);

  const configText = `/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.js to modify the generation of this file.
module.exports = ${JSON.stringify(config, null, 2)};`;

  const configPath = path.resolve('src/temp/config.js');

  console.log(`Writing runtime config to ${configPath}`);

  fs.writeFileSync(configPath, configText, { encoding: 'utf8' });
};

function transformScJssConfig() {
  // scjssconfig.json may not exist if you've never run setup
  // so if it doesn't we substitute a fake object
  // console.log(
  //   'process.env.npm_package_config_myPort',
  //   process.env.myssPort,
  // );

  let config;
  try {
    // eslint-disable-next-line global-require
    const mock = process.argv.some(arg => arg === '--mock');
    if (mock) {
      config = require('../scjssconfig.mock.json');
    } else {
      config = require('../scjssconfig.json');
    }
  } catch (e) {
    return {};
  }

  if (!config) return {};

  return {
    siteNameTemplateRoute: config.drx.siteNameTemplateRoute,
    sitecoreApiKey: config.sitecore.apiKey,
    sitecoreApiHost: config.sitecore.layoutServiceHost,
    googleMapsApiKey: config.drx.googleMapsApiKey,
    storeLogoutToken: config.drx.storeLogoutToken,
    gqlUrlToken: config.drx.gqlUrlToken,
    cookieDomain: config.drx.cookieDomain,
    deviceSupport: config.drx.deviceSupport,
    cochlearDotCom: config.drx.cochlearDotCom,
    drxMain: config.drx.drxMain,
    authorizeUser: config.drx.authorizeUser,
    cochlearMCR: config.drx.cochlearMCR,
    apiEndpoint: config.drx.apiEndpoint,
    storeLogout: config.drx.storeLogout,
    cimRecipientLogout: config.drx.cimRecipientLogout,
    UHDropdown: config.drx.UHDropdown,
    account: config.drx.account,
    address: config.drx.address,
    headerFooter: config.drx.headerFooter,
    orders: config.drx.orders,
    regions: config.drx.regions,
    auth0Host: config.drx.auth0Host,
    auth0ClientId: config.drx.auth0ClientId,
    auth0CustomDomain: config.drx.auth0CustomDomain,
    auth0LogoutRedirectUrl: config.drx.auth0LogoutRedirectUrl
};
}

function transformPackageConfig() {
  if (!packageConfig.config) return {};

  return {
    jssAppName: packageConfig.config.appName,
    defaultLanguage: packageConfig.config.language || 'en',
    graphQLEndpointPath:
      packageConfig.config.graphQLEndpointPath || null,
  };
}

/**
 * Adds the GraphQL endpoint URL to the config object, and ensures that components needed to calculate it are valid
 */
function addGraphQLConfig(baseConfig) {
  if (
    !baseConfig.graphQLEndpointPath ||
    typeof baseConfig.sitecoreApiHost === 'undefined'
  ) {
    console.error(
      'The `graphQLEndpointPath` and/or `layoutServiceHost` configurations were not defined. You may need to run `jss setup`.',
    );
    process.exit(1);
  }

  // eslint-disable-next-line no-param-reassign
  baseConfig.graphQLEndpoint = `${baseConfig.sitecoreApiHost}${baseConfig.graphQLEndpointPath}?sc_apikey=${baseConfig.sitecoreApiKey}`;
}
